services:
  web:
    image: junman140/zyrachains-frontend:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:8000:8000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
