export const language_ko={
    "nav.home": "홈",
    "nav.cexs": "CEXs 및 코어 팀",
    "nav.operations": "작업",
    "nav.transactions": "거래",
    "nav.blocks": "블록",
    "nav.nodes": "노드",
    "nav.stats": "통계",
    "stats.accounts": "계정 분포",
    "stats.unlocks": "Pi 잠금 해제 (30일)",
    "stats.unlocks_monthly": "월간 Pi 잠금 해제",
    "stats.domain_auction": "도메인 경매 통계",
    "stats.largest_tx": "최대 거래",
    "stats.migrate": "메인넷 이동 통계",
    "search.placeholder": "검색...",
    "operations.self_transfer": "자체 송금",
    "operations.domain_auction": "도메인 경매",
    "operations.claim_claimable_balance": "π 수령",
    "operations.create_account": "계정 생성",
    "operations.payment": "결제",
    "operations.path_payment_strict_receive": "엄격한 수신 경로 결제",
    "operations.path_payment_strict_send": "엄격한 송신 경로 결제",
    "operations.manage_sell_offer": "판매 제안 관리",
    "operations.create_passive_sell_offer": "수동 판매 제안 생성",
    "operations.set_options": "옵션 설정",
    "operations.change_trust": "신뢰 변경",
    "operations.allow_trust": "신뢰 허용",
    "operations.account_merge": "계정 병합",
    "operations.inflation": "인플레이션",
    "operations.manage_data": "데이터 관리",
    "operations.bump_sequence": "시퀀스 증가",
    "operations.manage_buy_offer": "구매 제안 관리",
    "operations.create_passive_buy_offer": "수동 구매 제안 생성",
    "operations.create_claimable_balance": "수령 가능 잔액 생성",
    "operations.claim_claimable_balance_atom": "수령 가능 잔액 수령",
    "operations.deposit": "입금",
    "operations.withdraw": "출금",
    "operations.pay": "지불",
    "operations.to": "대상",
    "operations.from": "출발",
    "operations.claimant": "수령자",
    "operations.with_starting_balance": "초기 잔액 포함",
    "operations.claim": "수령",
    "operations.heading": "Pi 네트워크 블록체인의 최신 작업 탐색",
    "operations.title": "Pi 네트워크의 최신 작업",
    "operations.description": "Pi 네트워크 블록체인의 최신 작업을 탐색하세요.",
    "operations.source_account": "소스 계정",
    "operations.operation": "작업",
    "operations.amount": "금액",
    "operations.tx": "거래",
    "operations.time": "시간",
    "pagination.previous": "이전",
    "pagination.next": "다음",
    "pagination.page": "페이지",
    "account.title": "계정 {{address}} - Pi 네트워크 탐색기",
    "account.heading": "계정 상세정보",
    "account.heading_with_address": "계정 {{address}}",
    "account.description": "Pi 네트워크의 계정 {{address}} 상세정보입니다.",
    "account.loading": "계정 상세정보 로딩 중...",
    "account.not_found": "계정을 찾을 수 없습니다.",
    "account.scam_warning_title": "사기 경고",
    "account.scam_warning_description": "이 지갑 주소는 커뮤니티 보고에 따라 안전하지 않은 것으로 표시되었습니다. 사기, 개인 키 손상 또는 무단 액세스와 관련이 있을 수 있습니다. 거래를 하기 전에 주의하세요.",
    "account.overview": "개요",
    "account.available_balance": "사용 가능한 잔액",
    "account.last_modified_time": "마지막 수정 시간",
    "account.locking": "잠금",
    "account.total_locking": "총 잠금 ({{count}}개 항목)",
    "account.next_unlock_time": "다음 잠금 해제 시간",
    "account.claimable": "수령 가능",
    "account.amount": "금액",
    "account.number_of_items": "항목 수",
    "account.over_100_items": "100개 이상 항목",
    "account.tx_hash": "트랜잭션 해시",
    "account.operation_count": "작업 수",
    "account.fee": "수수료",
    "account.created_at": "생성 시간",
    "account.account": "계정",
    "account.effect": "효과",
    "account.sponsor": "스폰서",
    "account.predicate": "조건",
    "account.create_time": "생성 시간",
    "account.latest_100_claimable": "최근 100개 수령 가능 잔액",
    "account.tabs.operations": "작업",
    "account.tabs.transactions": "트랜잭션",
    "account.tabs.effects": "효과",
    "account.tabs.claimable_balances": "수령 가능 잔액",
    "effects.account_credited": "계정 입금",
    "effects.account_debited": "계정 출금",
    "effects.account_created": "계정 생성",
    "effects.claimable_balance_created": "수령 가능 잔액 생성",
    "effects.claimable_balance_claimed": "수령 가능 잔액 수령됨",
    "effects.claimable_balance_claimant_created": "수령 가능 잔액 수령자 생성",
    "effects.account_removed": "계정 삭제됨",
    "effects.account_thresholds_updated": "계정 임계값 업데이트됨",
    "effects.account_home_domain_updated": "계정 홈 도메인 업데이트됨",
    "effects.account_flags_updated": "계정 플래그 업데이트됨",
    "effects.account_inflation_destination_updated": "계정 인플레이션 대상 업데이트됨",
    "effects.signer_created": "서명자 생성됨",
    "effects.signer_removed": "서명자 제거됨",
    "effects.signer_updated": "서명자 업데이트됨",
    "effects.trustline_removed": "신뢰선 제거됨",
    "effects.trustline_updated": "신뢰선 업데이트됨",
    "effects.trustline_authorized": "신뢰선 승인됨",
    "effects.trustline_deauthorized": "신뢰선 승인 취소됨",
    "effects.offer_created": "제안 생성됨",
    "effects.offer_removed": "제안 제거됨",
    "effects.offer_updated": "제안 업데이트됨",
    "effects.trade": "거래 실행됨",
    "effects.data_created": "데이터 생성됨",
    "effects.data_removed": "데이터 제거됨",
    "effects.data_updated": "데이터 업데이트됨",
    "effects.sequence_bumped": "시퀀스 증가됨",
    "effects.liquidity_pool_created": "유동성 풀 생성됨",
    "effects.liquidity_pool_removed": "유동성 풀 제거됨",
    "effects.liquidity_pool_deposited": "유동성 풀 입금됨",
    "effects.liquidity_pool_withdrew": "유동성 풀 출금됨",
    "effects.liquidity_pool_trade": "유동성 풀 거래",
    "effects.liquidity_pool_revoked": "유동성 풀 취소됨",
    "effects.contract_credited": "계약 입금됨",
    "effects.contract_debited": "계약 출금됨",
    "effects.claimable_balance_sponsorship_removed": "수령 가능 잔액 스폰서십 제거됨",
    "account_stats.heading": "Pi 계정 통계 - 잔액 분포 및 상위 계정",
    "account_stats.title": "Pi 계정 통계 - 잔액 분포 및 상위 계정",
    "account_stats.description": "Pi 네트워크에서 가장 부유한 Pi 계정과 전반적인 잔액 분포를 확인하세요.",
    "account_stats.intro_text": "모든 계정에 걸친 Pi의 분포를 탐색하고 상위 Pi 보유자를 확인하세요.",
    "account_stats.distribution_chart_title": "Pi 보유자 분포",
    "account_stats.categories_title": "분포 카테고리",
    "account_stats.top_accounts_title": "상위 Pi 계정",
    "account_stats.accounts": "계정",
    "account_stats.of_total": "전체 중",
    "account_stats.table.category": "카테고리",
    "account_stats.table.balance_range": "잔액 범위",
    "account_stats.table.usd_value": "USD 가치",
    "account_stats.table.accounts": "계정",
    "account_stats.table.percentage": "전체 중 %",
    "account_stats.table.total": "합계",
    "account_stats.table.rank": "순위",
    "account_stats.table.account": "계정",
    "account_stats.table.balance": "잔액",
    "account_stats.table.value": "가치",
    "account_stats.table.supply_percentage": "공급량 중 %",
    "account_stats.categories.whales": "고래",
    "account_stats.categories.sharks": "상어",
    "account_stats.categories.dolphins": "돌고래",
    "account_stats.categories.tunas": "참치",
    "account_stats.categories.fish": "물고기",
    "account_stats.categories.shrimps": "새우",
    "account_stats.categories.plankton": "플랑크톤",
    "account_stats.categories.microbes": "미생물",
    "number.billion_short": "십억",
    "number.million_short": "백만",
    "number.thousand_short": "천",
    "common.loading": "로딩 중...",
    "common.sponsored": "스폰서",
    "common.ad": "광고",
    "common.ad_not_available": "귀하의 지역에서 스폰서 콘텐츠를 이용할 수 없습니다",
    "blocks.heading": "Pi 네트워크 블록체인의 최신 블록 탐색",
    "blocks.title": "Pi 네트워크의 최신 블록",
    "blocks.description": "Pi 네트워크 블록체인의 최신 블록을 탐색하세요.",
    "blocks.sequence": "시퀀스",
    "blocks.hash": "해시",
    "blocks.transactions": "트랜잭션",
    "blocks.operations": "작업",
    "blocks.time": "시간",
    "blocks.successful": "성공",
    "blocks.failed": "실패",
    "block.title": "블록 #{{sequence}} - Pi 네트워크 탐색기",
    "block.heading": "블록 #{{sequence}}",
    "block.description": "Pi 네트워크 블록체인의 블록 #{{sequence}} 상세 정보.",
    "block.loading": "블록 상세 정보 로딩 중...",
    "block.not_found": "블록을 찾을 수 없습니다.",
    "block.information": "블록 정보",
    "block.hash": "해시",
    "block.previous_hash": "이전 해시",
    "block.sequence": "시퀀스",
    "block.time": "시간",
    "block.total_coins": "총 코인",
    "block.fee_pool": "수수료 풀",
    "block.base_fee": "기본 수수료",
    "block.base_reserve": "기본 예비금",
    "block.protocol_version": "프로토콜 버전",
    "block.tx_hash": "트랜잭션 해시",
    "block.operation_count": "작업 수",
    "block.fee": "수수료",
    "block.created_at": "생성 시간",
    "block.tabs.transactions": "트랜잭션",
    "block.tabs.operations": "작업",
    "block.tabs.effects": "효과",
    "cex.heading": "CEX 및 코어 팀 계정 통계",
    "cex.title": "Pi 네트워크의 CEX 및 코어 팀 계정",
    "cex.description": "Pi 네트워크 블록체인의 CEX 및 코어 팀 계정을 탐색하세요.",
    "cex.wallet_balances": "CEX 지갑 잔액",
    "cex.core_team_wallets": "Pi 코어 팀 지갑",
    "cex.cmc_ranking": "CMC 순위",
    "cex.exchange": "거래소",
    "cex.chart_link": "차트 링크",
    "cex.signup_link": "가입 링크",
    "cex.wallet_address": "지갑 주소",
    "cex.balance_pi": "잔액 (Pi)",
    "cex.balance_usd": "잔액 (USD)",
    "cex.chart": "차트",
    "cex.signup": "가입",
    "cex.total": "총합",
    "cex.note": "참고",
    "cex.pi_foundation": "Pi 재단",
    "cex.total_in": "총 입금 (최근 24시간)",
    "cex.total_out": "총 출금 (최근 24시간)",
    "cex.net_difference": "순 흐름 (최근 24시간)",
    "cex.flow_data_updated": "흐름 데이터 마지막 업데이트 (30분마다 갱신)",
    "cex.actions": "작업",
    "cex.filter_transactions_tooltip": "이 주소의 거래 필터링",
    "cex.filter_txs_button": "거래 필터",
    "pct.nav": "코어 팀",
    "cex_monitor.nav": "거래소",
    "pct.title": "코어 팀 지갑 추적",
    "pct.subtitle": "확인된 잔액 변화만 보여줍니다.",
    "pct.tab_wallets": "지갑",
    "pct.tab_updates": "업데이트",
    "pct.tab_history": "기록",
    "pct.stat_tracked": "추적 지갑 수",
    "pct.stat_starting": "시작 잔액 합계",
    "pct.stat_current": "현재 잔액 합계",
    "pct.stat_changes": "확인된 변동 수",
    "pct.stat_total_out": "총 유출",
    "pct.stat_24h": "24시간 순변동",
    "pct.section_wallets": "코어 팀 지갑 목록",
    "pct.section_updates": "최근 변동(7일)",
    "pct.section_history": "최신 변동",
    "pct.latest_check": "마지막 확인:",
    "pct.scan_running": "스캔 진행 중",
    "pct.prev": "이전",
    "pct.next": "다음",
    "pct.wallets_index": "개 지갑",
    "pct.footer_note": "탐색기 링크는 공식 Pi 블록 탐색기를 엽니다.",
    "pct.col_wallet": "지갑",
    "pct.col_old": "이전 잔액",
    "pct.col_new": "새 잔액",
    "pct.col_change": "변동",
    "pct.col_detected": "감지 시각",
    "pct.col_ledger": "원장",
    "pct.no_changes": "아직 기록이 없습니다. 나중에 다시 확인하세요.",
    "pct.loading": "로딩 중…",
    "pct.load_more": "더 보기",
    "pct.summary_error": "요약을 불러오지 못했습니다.",
    "cex_monitor.title": "거래소 지갑 추적기",
    "cex_monitor.subtitle": "확인된 잔액 변동이 있는 거래소 지갑입니다.",
    "cex_monitor.tab_wallets": "지갑",
    "cex_monitor.tab_updates": "업데이트",
    "cex_monitor.tab_history": "기록",
    "cex_monitor.stat_tracked": "추적 중인 지갑",
    "cex_monitor.stat_starting": "시작 잔액",
    "cex_monitor.stat_current": "현재 잔액",
    "cex_monitor.stat_changes": "확인된 변동",
    "cex_monitor.stat_total_out": "총 유출",
    "cex_monitor.stat_24h": "24시간 순변동",
    "cex_monitor.section_wallets": "거래소 지갑 목록",
    "cex_monitor.section_updates": "최근 변동 (7일)",
    "cex_monitor.section_history": "최신 확인된 변동",
    "cex_monitor.latest_check": "마지막 확인:",
    "cex_monitor.scan_running": "스캔 진행 중",
    "cex_monitor.prev": "이전",
    "cex_monitor.next": "다음",
    "cex_monitor.wallets_index": "개 지갑",
    "cex_monitor.footer_note": "탐색기 링크는 공식 Pi 블록 탐색기를 엽니다.",
    "cex_monitor.col_wallet": "지갑",
    "cex_monitor.col_old": "이전 잔액",
    "cex_monitor.col_new": "새 잔액",
    "cex_monitor.col_change": "변동",
    "cex_monitor.col_detected": "감지 시각",
    "cex_monitor.col_ledger": "원장",
    "cex_monitor.no_changes": "아직 확인된 변동이 없습니다. 나중에 다시 확인하세요.",
    "cex_monitor.loading": "로딩 중…",
    "cex_monitor.load_more": "더 보기",
    "cex_monitor.summary_error": "서버에서 CEX 요약을 불러오지 못했습니다.",
    "contact.heading": "문의하기",
    "contact.title": "PiScan에 문의하기",
    "contact.description": "질문이나 피드백이 있으시면 PiScan에 문의하세요.",
    "contact.intro_text": "질문이 있으시면 다음 주소로 연락해 주세요",
    "contact.success_message": "문의해 주셔서 감사합니다! 곧 답변 드리겠습니다.",
    "contact.form.name": "이름",
    "contact.form.email": "이메일",
    "contact.form.message": "메시지",
    "contact.form.submit": "메시지 보내기",
    "home.heading": "Pi 네트워크 거래, 지갑 및 통계 탐색",
    "home.title": "Pi 네트워크 거래, 지갑 및 통계 탐색",
    "home.description": "Pi 네트워크 거래, 지갑 및 통계 탐색",
    "home.market_cap": "시가총액",
    "home.price": "가격",
    "home.24h_change": "24시간 변동",
    "home.pi_supply": "Pi 공급량",
    "home.circulating": "유통량",
    "home.locked": "잠금량",
    "home.cex_balance_total": "CEX 잔액 (총)",
    "home.view_all": "모두 보기",
    "home.network_stats": "네트워크 통계",
    "home.blocks": "블록",
    "home.tps": "TPS",
    "home.latest_transactions": "최근 거래",
    "home.signature": "서명",
    "home.time": "시간",
    "home.block": "블록",
    "home.ops": "작업 수",
    "home.latest_operations": "최근 작업",
    "home.source_account": "소스 계정",
    "home.operation": "작업",
    "home.amount": "금액",
    "home.tx": "거래",
    "nodes.heading": "Pi 네트워크 노드 맵 및 네트워크 통계",
    "nodes.title": "Pi 네트워크 노드 및 검증자",
    "nodes.description": "Pi 네트워크 노드, 검증자 및 네트워크 토폴로지를 탐색하세요. 노드의 전 세계 분포 및 연결성을 확인하세요.",
    "nodes.active_nodes": "활성 노드",
    "nodes.validators": "검증자",
    "nodes.known_peers": "알려진 피어",
    "nodes.disconnected_nodes": "연결 끊긴 노드",
    "nodes.network_graph": "네트워크 그래프",
    "nodes.node_types": "노드 유형",
    "nodes.validator": "검증자",
    "nodes.watcher": "관찰자",
    "nodes.disconnected_private": "연결 끊김/비공개",
    "nodes.click_to_highlight": "노드를 클릭하여 연결을 강조 표시",
    "nodes.global_distribution": "전 세계 분포",
    "nodes.mapped_nodes": "지도에 표시된 노드",
    "nodes.node_details": "노드 세부 정보",
    "nodes.nodes": "노드",
    "nodes.address": "주소",
    "nodes.type": "유형",
    "nodes.location": "위치",
    "nodes.isp": "인터넷 서비스 제공업체",
    "nodes.version": "버전",
    "nodes.trust": "신뢰",
    "nodes.trusted_by": "신뢰 수",
    "nodes.status": "상태",
    "nodes.status.connected": "연결됨",
    "nodes.status.disconnected": "연결 끊김",
    "nodes.status.private": "비공개",
    "nodes.active_quorum_sets": "활성 쿼럼 세트",
    "nodes.active": "활성",
    "nodes.quorum_hash": "쿼럼 해시",
    "nodes.node_id": "노드 ID",
    "nodes.unknown": "알 수 없음",
    "nodes.core_team": "코어 팀",
    "nodes.tooltip.node_id": "노드 ID",
    "nodes.tooltip.address": "주소",
    "nodes.tooltip.type": "유형",
    "nodes.tooltip.status": "상태",
    "nodes.tooltip.version": "버전",
    "nodes.tooltip.location": "위치",
    "nodes.tooltip.not_accessible": "접근 불가",
    "nodes.phantom_validators": "팬텀 검증자",
    "nodes.country_statistics": "국가별 통계",
    "nodes.city_statistics": "도시별 통계",
    "nodes.online_nodes_only": "온라인 노드만",
    "nodes.country": "국가",
    "nodes.city": "도시",
    "nodes.connected_nodes": "연결된 노드",
    "nodes.no_country_data": "국가 데이터 없음",
    "nodes.no_city_data": "도시 데이터 없음",
    "nodes_testnet.heading": "Pi 네트워크 테스트넷 노드 통계",
    "nodes_testnet.title": "Pi 네트워크 테스트넷 노드",
    "nodes_testnet.description": "Pi 네트워크 테스트넷 노드 통계 및 전 세계 분포를 탐색하세요.",
    "nodes_testnet.summary_title": "테스트넷 노드 개요",
    "nodes_testnet.summary_description": "Pi 네트워크 테스트넷 노드 및 활동 수준의 실시간 통계입니다.",
    "nodes_testnet.total_peers": "총 피어",
    "nodes_testnet.active_peers": "활성 피어",
    "nodes_testnet.activity_rate": "활동률",
    "nodes_testnet.country_statistics": "국가별 통계",
    "nodes_testnet.city_statistics": "도시별 통계",
    "nodes_testnet.country": "국가",
    "nodes_testnet.city": "도시",
    "nodes_testnet.total_nodes": "총 노드",
    "nodes_testnet.active_nodes": "활성 노드",
    "nodes_testnet.active_rate": "활성 비율",
    "report_scam.heading": "사기 지갑 신고",
    "report_scam.title": "PiScan에서 사기 지갑 신고",
    "report_scam.description": "사기 또는 부정 행위와 관련된 지갑 주소를 신고하세요.",
    "report_scam.intro_text": "사기 또는 부정 행위와 관련된 의심스러운 지갑 주소를 발견하셨다면, 아래 양식을 사용하여 신고해 주세요. 저희 팀이 제출 내용을 검토하고, 사기로 확인되면 커뮤니티에 경고하기 위해 PiScan에서 해당 지갑을 \"사기\"로 표시할 것입니다.",
    "report_scam.success_message": "신고해 주셔서 감사합니다! 저희 팀이 가능한 한 빨리 검토하겠습니다.",
    "report_scam.form.wallet_address": "지갑 주소",
    "report_scam.form.wallet_placeholder": "사기 지갑 주소를 입력하세요",
    "report_scam.form.reason": "신고 이유",
    "report_scam.form.reason_placeholder": "이 지갑이 사기 활동으로 의심되는 이유를 설명하세요",
    "report_scam.form.email": "이메일 (선택사항)",
    "report_scam.form.email_placeholder": "이메일을 입력하세요 (선택사항)",
    "report_scam.form.email_note": "추가 정보를 위해 연락드릴 수 있습니다.",
    "report_scam.form.submit": "신고 제출",
    "transaction.title": "Pi 네트워크의 트랜잭션 #{{id}}",
    "transaction.heading": "트랜잭션 세부정보",
    "transaction.description": "Pi 네트워크 블록체인의 트랜잭션 #{{id}} 세부정보입니다.",
    "transaction.loading": "트랜잭션 세부정보를 로드 중...",
    "transaction.not_found": "트랜잭션을 찾을 수 없습니다.",
    "transaction.hash": "해시",
    "transaction.ledger_block": "원장 (블록)",
    "transaction.result": "결과",
    "transaction.source_account": "소스 계정",
    "transaction.fee_account": "수수료 계정",
    "transaction.fee": "수수료",
    "transaction.operation_count": "작업 수",
    "transaction.summary": "요약",
    "transaction.operations": "작업",
    "transaction.effects": "효과",
    "transaction.account": "계정",
    "transaction.operation": "작업",
    "transaction.effect": "효과",
    "transaction.amount": "금액",
    "transaction.successful": "성공",
    "transaction.failed": "실패",
    "transaction.loading_details": "트랜잭션 세부정보를 로드 중...",
    "transaction.with_operations": "{{count}}개 작업이 포함된 트랜잭션",
    "transaction.core_team_distributed": "Pi 코어 팀이 배포함",
    "transaction.to": "대상",
    "transaction.accounts": "계정",
    "transaction.locked_for_days": ", {{days}}일 동안 잠금됨",
    "transaction.locked_range_days": ", 잠금 기간은 {{minDays}}일에서 {{maxDays}}일까지 다양함",
    "transaction.created_at": "생성 시간",
    "unlock_stats.heading": "Pi 잠금 해제 통계 - 향후 30일",
    "unlock_stats.title": "Pi 잠금 해제 통계 - 향후 30일",
    "unlock_stats.description": "향후 30일 동안의 예상 Pi 암호화폐 잠금 해제 통계를 확인하세요.",
    "unlock_stats.intro_text": "향후 30일 동안의 Pi 잠금 해제는 사용자가 잠근 것이나 Pi 코어 팀이 배포한 수령 가능 잔액을 기반으로 합니다. 아직 수령 가능 잔액에 포함되지 않은 미공개 Pi는 추적할 수 없습니다. 정기적으로 업데이트를 확인하세요. 모든 시간은 UTC입니다.",
    "unlock_stats.today_note": "오늘의 잠금 해제 금액은 지금부터 하루가 끝날 때까지(UTC) 잠금 해제될 남은 Pi를 나타냅니다.",
    "unlock_stats.updated_at": "데이터 업데이트:",
    "unlock_stats.unknown": "알 수 없음",
    "unlock_stats.total_locked": "총 잠긴 Pi",
    "unlock_stats.total_next_30": "향후 30일 총 잠금 해제",
    "unlock_stats.of_total_locked": "총 잠긴 금액의",
    "unlock_stats.avg_daily": "일일 평균 잠금 해제",
    "unlock_stats.per_day": "일일",
    "unlock_stats.highest_day": "최고 일자",
    "unlock_stats.on": "날짜",
    "unlock_stats.chart_title": "Pi 잠금 해제 차트 - 향후 30일",
    "unlock_stats.data_table": "잠금 해제 데이터 테이블",
    "unlock_stats.date": "날짜",
    "unlock_stats.amount": "금액",
    "unlock_stats.value": "가치",
    "unlock_stats.pi_unlock": "Pi 잠금 해제",
    "unlock_stats.y_axis_label": "Pi 잠금 해제 (백만 단위)",
    "unlock_stats.monthly_heading": "월별 Pi 언락 통계",
    "unlock_stats.monthly_title": "월별 Pi 언락 통계",
    "unlock_stats.total_next_12": "향후 12개월 총 잠금 해제",
    "unlock_stats.monthly_description": "월별 Pi 암호화폐 언락 통계를 확인하세요",
    "unlock_stats.monthly_intro_text": "월별 Pi 암호화폐 언락 통계를 확인하세요.",
    "unlock_stats.monthly_note": "통계는 유효한 언락 요청을 기준으로 합니다.",
    "unlock_stats.monthly_chart_title": "월별 Pi 언락 통계 차트",
    "unlock_stats.total_forecast": "총 통계",
    "unlock_stats.monthly_data_table": "월별 언락 데이터",
    "unlock_stats.total_locking": "총 잠금 수량",
    "unlock_stats.avg_monthly": "월평균",
    "unlock_stats.highest_month": "최고 언락 월",
    "unlock_stats.per_month": "월별",
    "unlock_stats.in": "내",
    "unlock_stats.month": "월",
    "unlock_stats.view_daily": "일별 언락 통계 보기",
    "unlock_stats.view_monthly": "월별 언락 통계 보기",
    "common.loading_error": "데이터를 로드하는 중 오류가 발생했습니다. 나중에 다시 시도해 주세요.",
    "settings.aria_label": "설정 열기",
    "settings.language": "언어",
    "settings.appearance": "외관",
    "settings.dark_mode": "다크 모드",
    "settings.light": "라이트",
    "settings.dark": "다크",
    "transactios.heading": "Pi 네트워크 블록체인의 최신 거래 탐색",
    "transactions.title": "Pi 네트워크의 최신 거래",
    "transactions.description": "Pi 네트워크 블록체인의 최신 거래를 탐색하세요.",
    "domain_auction_stats.heading": "Pi 도메인 경매 통계",
    "domain_auction_stats.title": "Pi 도메인 경매 통계 | Pi 네트워크 통계",
    "domain_auction_stats.description": "Pi 네트워크 도메인 경매 분석, 다양한 가격대별 입찰 분포 및 총 입찰된 Pi를 표시합니다.",
    "domain_auction_stats.intro_text": "이 페이지는 Pi 도메인 경매에 대한 분석을 제공하며, 다양한 가격대별 입찰 분포를 강조합니다.",
    "domain_auction_stats.last_updated": "최종 업데이트",
    "domain_auction_stats.summary_title": "경매 입찰 요약",
    "domain_auction_stats.total_bids": "총 입찰 수",
    "domain_auction_stats.total_pi_bid": "총 입찰된 Pi",
    "domain_auction_stats.estimated_value": "예상 가치 (USD)",
    "domain_auction_stats.pi_price": "현재 Pi 가격",
    "domain_auction_stats.distribution_title": "입찰 분포",
    "domain_auction_stats.chart_title": "입찰 가격 분포",
    "domain_auction_stats.details_title": "실시간 입찰 내역",
    "domain_auction_stats.bids": "입찰",
    "domain_auction_stats.of_total": "총 입찰 중",
    "domain_auction_stats.bid_count": "입찰 수",
    "domain_auction_stats.ranges.low": "낮은 입찰",
    "domain_auction_stats.ranges.medium": "일반 입찰",
    "domain_auction_stats.ranges.high": "고급 입찰",
    "domain_auction_stats.ranges.premium": "프리미엄 입찰",
    "domain_auction_stats.ranges.elite": "최상급 입찰",
    "domain_auction_stats.table.price_range": "입찰 가격 범위",
    "domain_auction_stats.table.bid_count": "입찰 수",
    "domain_auction_stats.table.percentage": "비율",
    "domain_auction_stats.table.total": "총 입찰",
    "domain_auction_stats.highest_bid": "최고 입찰가",
    "domain_auction_stats.top_bids_title": "최고 입찰 목록",
    "domain_auction_stats.table.account": "계정",
    "domain_auction_stats.table.bid_amount": "입찰 금액",
    "domain_auction_stats.table.usd_value": "USD 가치",
    "largest_tx.heading": "최대 Pi 거래 (최근 24시간)",
    "largest_tx.title": "최근 24시간 동안의 최대 Pi 거래 - PiScan",
    "largest_tx.description": "최근 24시간 동안 Pi Network 블록체인에서 가장 큰 Pi 거래를 탐색하세요.",
    "largest_tx.list_heading": "거래량 기준 상위 거래 (최근 24시간)",
    "largest_tx.rank": "순위",
    "largest_tx.transaction": "거래",
    "largest_tx.account": "계정",
    "largest_tx.amount": "수량 (π)",
    "largest_tx.date": "날짜 & 시간",
    "largest_tx.no_data": "최근 24시간 동안 거래 데이터가 없습니다.",
    "largest_tx.fetch_error": "거래 데이터를 불러올 수 없습니다.",
    "largest_tx.loading": "최대 거래 로딩 중...",
    "largest_tx.largest_amount": "최대 거래 금액 (최근 24시간)",
    "largest_tx.latest_large_tx": "최근 대규모 거래 (최근 24시간)",
    "largest_tx.total_value": "총 가치 (상위 100개 거래, 최근 24시간)",
    "migrate_stats.heading": "Pi 이동 통계",
    "migrate_stats.title": "Pi 메인넷 마이그레이션 통계 - PiScan",
    "migrate_stats.description": "최근 며칠 동안의 Pi 메인넷 이동 통계를 추적하세요.",
    "migrate_stats.last_updated": "마지막 업데이트",
    "migrate_stats.daily_migration": "일일 Pi 이동량",
    "migrate_stats.daily_stats": "일별 이동 통계",
    "migrate_stats.loading": "이동 통계 로딩 중...",
    "migrate_stats.no_data": "이동 데이터가 없습니다.",
    "migrate_stats.fetch_error": "이동 데이터를 불러올 수 없습니다.",
    "migrate_stats.date": "날짜",
    "migrate_stats.amount": "수량 (π)",
    "migrate_stats.percentage": "비율 (%)",
    "migrate_stats.total": "총계",
    "migrate_stats.pi_migrated": "총 이동된 Pi",
    "migrate_stats.date_label": "날짜: {{date}}",
    "migrate_stats.usd_value": "USD 가치",
    "migrate_stats.at_price": "현재 가격 기준",
    "migrate_stats.current_price_note": "USD 가치는 현재 Pi 가격 {{price}} π 당 기준으로 계산됩니다.",
    "transactions_filter.heading": "거래 필터",
    "transactions_filter.title": "거래 필터 | Pi Scan",
    "transactions_filter.description": "주소, 금액 및 기타 기준에 따라 Pi Network 거래를 필터링하고 검색합니다.",
    "transactions_filter.address_required_error": "주소를 입력해야 합니다.",
    "transactions_filter.min_amount_required_error": "최소 금액을 입력해야 합니다.",
    "transactions_filter.amount_too_low_error": "금액은 10,000보다 작을 수 없습니다.",
    "transactions_filter.min_exceeds_max_error": "최소 금액은 최대 금액을 초과할 수 없습니다.",
    "transactions_filter.filter_options": "필터 옵션",
    "transactions_filter.address": "주소",
    "transactions_filter.address_placeholder": "계정 주소 입력",
    "transactions_filter.min_amount": "최소 금액 (Pi)",
    "transactions_filter.min_amount_placeholder": "예: 10000",
    "transactions_filter.max_amount": "최대 금액 (Pi)",
    "transactions_filter.max_amount_placeholder": "예: 100000",
    "transactions_filter.apply_filters": "적용",
    "transactions_filter.clear": "초기화",
    "transactions_filter.no_results": "조건에 맞는 거래를 찾을 수 없습니다.",
    "transactions_filter.results": "결과",
    "transactions_filter.table.hash": "거래 해시",
    "transactions_filter.table.time": "시간",
    "transactions_filter.table.from": "보낸 주소",
    "transactions_filter.table.to": "받는 주소",
    "transactions_filter.table.amount": "금액 (Pi)",
    "transactions_filter.apply_filters_prompt": "결과를 보려면 필터를 적용하세요.",
    "transactions_filter.table.tx": "거래",
    "transactions_filter.table.detail_button": "상세 보기",
    "transactions_filter.operation_text.payment": "{{from}}에서 {{to}}로 {{amount}} Pi 결제",
    "transactions_filter.operation_text.unknown": "알 수 없는 작업",
    "docs.heading": "개발자 문서",
    "docs.title": "문서 및 API - Zyrachain",
    "docs.description": "애플리케이션에 Pi 네트워크 데이터를 통합하기 위한 개발자 문서 및 API 엔드포인트입니다.",
    "docs.hero_subtitle": "Pi 네트워크 데이터로 놀라운 애플리케이션을 구축하세요. 포괄적인 API를 통해 실시간 블록체인 정보, DApp 목록 및 커뮤니티 기능에 액세스하세요.",
    "docs.features.real_time": "실시간 데이터",
    "docs.features.restful": "RESTful API",
    "docs.features.secure": "안전하고 신뢰할 수 있는",
    "docs.tabs.overview": "개요",
    "docs.tabs.endpoints": "API 엔드포인트",
    "docs.tabs.integration": "Pi 통합",
    "docs.tabs.examples": "예제",
    "docs.tabs.support": "지원",
    "docs.blockchain_data.title": "블록체인 데이터 API",
    "docs.blockchain_data.description": "실시간 Pi 네트워크 블록체인 정보에 액세스하세요",
    "docs.blockchain_data.features": [
      "거래 세부정보 및 내역",
      "블록 정보 및 통계",
      "계정 잔액 및 작업",
      "네트워크 지표 (TPS, 공급량 등)"
    ],
    "docs.dapp_directory.title": "DApp 디렉토리 API",
    "docs.dapp_directory.description": "Pi 네트워크 애플리케이션 검색 및 관리",
    "docs.dapp_directory.features": [
      "주요 DApp 둘러보기",
      "카테고리별 필터링",
      "새 애플리케이션 제출",
      "인기 앱 추적"
    ],
    "docs.getting_started.title": "시작하기",
    "docs.getting_started.description": "API 통합을 시작하려면 다음 단계를 따르세요",
    "docs.step1.title": "API 선택",
    "docs.step1.description": "블록체인 데이터, DApp 디렉토리 또는 커뮤니티 API 중에서 선택하세요",
    "docs.step2.title": "API 호출하기",
    "docs.step2.description": "표준 HTTP 메서드로 RESTful 엔드포인트를 사용하세요",
    "docs.step3.title": "놀라운 앱 구축",
    "docs.step3.description": "사용자를 위한 강력한 Pi 네트워크 애플리케이션을 만드세요",
    "docs.base_url.title": "기본 URL",
    "docs.base_url.description": "모든 API 요청은 이 기본 URL로 전송되어야 합니다",
    "docs.base_url.value": "https://clubhouse-pi.io/api/v1",
    "docs.endpoints.stats.title": "블록체인 통계",
    "docs.endpoints.stats.description": "실시간 Pi 네트워크 통계 가져오기",
    "docs.endpoints.stats.method": "GET",
    "docs.endpoints.stats.path": "/api/v1/stats",
    "docs.endpoints.stats.response": "TPS, 공급량 등을 포함한 네트워크 통계 반환",
    "docs.endpoints.transactions.title": "최신 거래",
    "docs.endpoints.transactions.description": "네트워크의 최신 거래 가져오기",
    "docs.endpoints.transactions.method": "GET",
    "docs.endpoints.transactions.path": "/api/v1/transactions",
    "docs.endpoints.transactions.params": "limit, cursor, order",
    "docs.endpoints.blocks.title": "최신 블록",
    "docs.endpoints.blocks.description": "네트워크의 최신 블록 가져오기",
    "docs.endpoints.blocks.method": "GET",
    "docs.endpoints.blocks.path": "/api/v1/blocks",
    "docs.endpoints.blocks.params": "limit, cursor, order",
    "docs.endpoints.account.title": "계정 세부정보",
    "docs.endpoints.account.description": "상세 계정 정보 가져오기",
    "docs.endpoints.account.method": "GET",
    "docs.endpoints.account.path": "/api/v1/accounts/{address}",
    "docs.endpoints.account.params": "address (필수)",
    "docs.endpoints.transaction.title": "거래 세부정보",
    "docs.endpoints.transaction.description": "상세 거래 정보 가져오기",
    "docs.endpoints.transaction.method": "GET",
    "docs.endpoints.transaction.path": "/api/v1/transactions/{hash}",
    "docs.endpoints.transaction.params": "hash (필수)",
    "docs.integration.title": "Pi 네트워크 통합",
    "docs.integration.description": "Pi 네트워크 인증 및 결제 통합 방법 알아보기",
    "docs.integration.auth.title": "인증",
    "docs.integration.auth.description": "애플리케이션에서 Pi 네트워크 인증 사용하기",
    "docs.integration.payments.title": "결제",
    "docs.integration.payments.description": "애플리케이션에서 Pi 결제 수락하기",
    "docs.examples.title": "코드 예제",
    "docs.examples.description": "일반적인 사용 사례를 위한 바로 사용 가능한 코드 예제",
    "docs.examples.javascript.title": "JavaScript/Node.js",
    "docs.examples.python.title": "Python",
    "docs.examples.curl.title": "cURL",
    "docs.support.title": "지원 및 리소스",
    "docs.support.description": "도움말 및 추가 리소스 찾기",
    "docs.support.community.title": "커뮤니티",
    "docs.support.community.description": "지원 및 토론을 위해 개발자 커뮤니티에 참여하세요",
    "docs.support.documentation.title": "문서",
    "docs.support.documentation.description": "포괄적인 가이드 및 튜토리얼",
    "docs.support.api_reference.title": "API 참조",
    "docs.support.api_reference.description": "완전한 API 엔드포인트 문서",
    "terms.heading": "서비스 약관",
    "terms.title": "서비스 약관 - Zyrachain",
    "terms.description": "Zyrachain 서비스 및 플랫폼 이용에 관한 약관입니다.",
    "terms.section1.title": "약관 동의",
    "terms.section1.content": "Zyrachain(\"서비스\")에 접근하고 이용함으로써, 귀하는 본 약관의 조항에 동의하고 이를 준수할 것에 동의합니다. 위 내용을 준수하지 않으실 경우, 본 서비스를 이용하지 마십시오.",
    "terms.section2.title": "사용 라이선스",
    "terms.section2.content": "Zyrachain 웹사이트의 자료(정보 또는 소프트웨어)를 개인적, 비상업적 일시적 열람 목적으로만 임시 다운로드할 수 있는 권한이 부여됩니다. 이는 라이선스 부여이지 소유권 이전이 아니며, 본 라이선스에 따라 다음 행위가 금지됩니다: 자료의 수정 또는 복사, 상업적 목적이나 공개 전시를 위한 자료 사용, Zyrachain 웹사이트에 포함된 소프트웨어의 리버스 엔지니어링 시도, 자료에서 저작권 또는 기타 소유권 표기 제거, 또는 자료를 타인에게 전송하거나 다른 서버에 \"미러링\"하는 행위.",
    "terms.section3.title": "면책 조항",
    "terms.section3.content": "Zyrachain 웹사이트의 자료는 '있는 그대로' 제공됩니다. Zyrachain은 명시적이든 묵시적이든 어떠한 보증도 하지 않으며, 상품성, 특정 목적에의 적합성, 지적 재산권 비침해 또는 기타 권리 침해에 대한 묵시적 보증을 포함한 모든 기타 보증을 부인합니다.",
    "terms.section4.title": "책임 제한",
    "terms.section4.content": "어떠한 경우에도 Zyrachain 또는 그 공급자는 Zyrachain 웹사이트의 자료 사용 또는 사용 불능으로 인해 발생하는 손해(데이터 손실, 이익 손실 또는 사업 중단으로 인한 손해를 포함하되 이에 국한되지 않음)에 대해 책임을 지지 않습니다.",
    "terms.section5.title": "자료의 정확성",
    "terms.section5.content": "Zyrachain 웹사이트에 표시되는 자료에는 기술적, 인쇄상 또는 사진상의 오류가 포함될 수 있습니다. Zyrachain은 웹사이트의 자료가 정확하거나 완전하거나 최신임을 보증하지 않습니다. Zyrachain은 언제든지 통지 없이 웹사이트에 포함된 자료를 변경할 수 있습니다.",
    "terms.section6.title": "링크",
    "terms.section6.content": "Zyrachain은 웹사이트에 링크된 모든 사이트를 검토하지 않았으며, 링크된 사이트의 내용에 대해 책임을 지지 않습니다. 링크의 포함이 Zyrachain의 해당 사이트에 대한 보증을 의미하지는 않습니다. 링크된 웹사이트의 이용은 사용자의 책임입니다.",
    "terms.section7.title": "수정",
    "terms.section7.content": "Zyrachain은 언제든지 통지 없이 웹사이트의 본 서비스 약관을 개정할 수 있습니다. 본 웹사이트를 이용함으로써 귀하는 당시 최신 버전의 서비스 약관에 동의하게 됩니다.",
    "terms.section8.title": "준거법",
    "terms.section8.content": "본 약관은 해당 관할권의 법률에 따라 규율되고 해석되며, 귀하는 해당 관할권 법원의 전속 관할권에 취소 불가능하게 복종합니다.",
    "terms.contact.title": "연락처 정보",
    "terms.contact.content": "본 서비스 약관에 대해 질문이 있으시면 다음 주소로 문의해 주십시오:",
    "terms.contact.email": "zyrachains@gmail.com",
    "contact.email": "zyrachains@gmail.com",
    "privacy.heading": "개인정보 처리방침",
    "privacy.title": "개인정보 처리방침 - Zyrachain Pi 네트워크 생태계 허브",
    "privacy.description": "당사가 귀하의 개인정보를 수집, 이용 및 보호하는 방법입니다.",
    "privacy.section1.title": "수집하는 정보",
    "privacy.section1.content": "당사는 귀하가 계정을 생성하거나, 당사에 연락하거나, 서비스를 이용할 때 직접 제공하는 정보를 수집합니다. 여기에는 이름, 이메일 주소, 지갑 주소 및 귀하가 제공하기로 선택한 기타 정보가 포함될 수 있습니다. 또한 귀하가 서비스를 이용할 때 IP 주소, 브라우저 유형, 운영 체제 및 이용 패턴을 포함한 특정 정보를 자동으로 수집합니다.",
    "privacy.section2.title": "정보 이용 방법",
    "privacy.section2.content": "당사는 수집한 정보를 서비스 제공, 유지 및 개선, 귀하와의 소통, 새로운 기능 개발, 그리고 사용자와 대중 보호를 위해 사용합니다. 또한 기술 공지, 업데이트, 보안 알림 및 지원 메시지를 보내기 위해 귀하의 정보를 사용할 수 있습니다.",
    "privacy.section3.title": "정보 공유",
    "privacy.section3.content": "당사는 본 방침에 명시된 경우를 제외하고 귀하의 동의 없이 제3자에게 귀하의 개인정보를 판매, 거래 또는 이전하지 않습니다. 당사는 웹사이트 운영 및 서비스 제공을 지원하는 서비스 제공업체와, 또는 법률이 요구하는 경우 귀하의 정보를 공유할 수 있습니다.",
    "privacy.section4.title": "데이터 보안",
    "privacy.section4.content": "당사는 무단 액세스, 변경, 공개 또는 파괴로부터 귀하의 개인정보를 보호하기 위해 적절한 보안 조치를 시행합니다. 그러나 인터넷을 통한 전송 방법이나 전자 저장 방법이 100% 안전한 것은 아닙니다.",
    "privacy.section5.title": "쿠키 및 추적",
    "privacy.section5.content": "당사는 웹사이트 경험 향상, 이용 패턴 분석 및 콘텐츠 개인화를 위해 쿠키 및 유사한 추적 기술을 사용합니다. 브라우저 설정을 통해 쿠키 설정을 제어할 수 있습니다.",
    "privacy.section6.title": "귀하의 권리",
    "privacy.section6.content": "귀하는 개인정보에 접근, 업데이트 또는 삭제할 권리가 있습니다. 또한 당사의 특정 통신을 거부할 수 있습니다. 이러한 권리를 행사하려면 아래 제공된 정보를 사용하여 당사에 문의하십시오.",
    "privacy.section7.title": "본 방침의 변경",
    "privacy.section7.content": "당사는 수시로 본 개인정보 처리방침을 업데이트할 수 있습니다. 변경 사항은 본 페이지에 새로운 방침을 게시하고 \"최종 업데이트\" 날짜를 업데이트하여 알려드립니다.",
    "privacy.contact.title": "문의하기",
    "privacy.contact.content": "본 개인정보 처리방침에 대해 질문이 있으시면 다음 주소로 문의해 주십시오:",
    "privacy.contact.email": "zyrachains@gmail.com",
    "report.heading": "사기 또는 부정 행위 신고",
    "report.title": "사기 신고 - Zyrachain Pi 네트워크 생태계 허브",
    "report.description": "Pi 네트워크 커뮤니티 보호를 위해 의심스러운 활동이나 사기 행위를 신고하세요.",
    "report.intro": "사기 또는 부정 행위로 의심되는 지갑 주소, 프로젝트 또는 활동을 발견하셨다면 아래 양식을 사용하여 신고해 주세요. 저희 팀이 제출 내용을 검토하고 커뮤니티 보호를 위해 적절한 조치를 취하겠습니다.",
    "report.success_message": "신고해 주셔서 감사합니다! 보안 팀이 정보를 검토하고 적절한 조치를 취하겠습니다. Pi 네트워크 생태계를 안전하게 유지하는 데 도움을 주셔서 감사합니다.",
    "report.form.wallet_address": "지갑 주소 (해당되는 경우)",
    "report.form.wallet_address_placeholder": "의심스러운 지갑 주소 입력",
    "report.form.description": "사기/부정 행위 설명",
    "report.form.description_placeholder": "무슨 일이 있었는지, 왜 이것이 사기 또는 부정 행위라고 생각하는지 자세히 설명해 주세요...",
    "report.form.evidence": "증거 (선택사항)",
    "report.form.evidence_placeholder": "신고를 뒷받침하는 추가 증거, 스크린샷 또는 링크...",
    "report.form.contact": "연락처 정보 (선택사항)",
    "report.form.contact_placeholder": "후속 질문을 위해 연락 가능한 이메일 주소",
    "report.form.submit": "신고 제출",
    "report.info.title": "신고 대상",
    "report.info.description": "다음 중 하나를 신고해 주세요:",
    "report.info.items": [
      "가짜 Pi 네트워크 프로젝트 또는 애플리케이션",
      "피싱 시도 또는 가짜 웹사이트",
      "사기와 관련된 의심스러운 지갑 주소",
      "가짜 경품 또는 에어드롭",
      "공식 Pi 네트워크 계정 사칭",
      "기타 사기 행위"
    ],
    "report.info.note": "참고: 당사는 모든 신고를 진지하게 받아들이고 각 사례를 철저히 조사합니다. 귀하의 개인정보는 전 과정에서 보호됩니다.",
    "assets.search_placeholder": "코드 또는 발행자로 검색...",
    "assets.testnet_warning": "Pi Network 메인넷 데이터입니다. 메인넷에 아직 사용자 정의 자산이 없습니다."
}