export  const language_tr={
    'nav.home': 'Ana Sayfa',
    'nav.cexs': "CEX'ler ve Çekirdek Takım",
    'nav.operations': 'Operasyonlar',
    'nav.transactions': 'İşlemler',
    'nav.blocks': 'Bloklar',
    'nav.nodes': 'Düğümler',
    'nav.stats': 'İstatistikler',
    'stats.accounts': 'Hesap Dağılımı',
    'stats.unlocks': 'Pi Kilidini Açma (30 Gün)',
    'stats.unlocks_monthly': 'Pi Kilidini Açma (Aylık)',
    'stats.domain_auction': 'Alan Adı Müzayedesi',
    'stats.largest_tx': 'En Büyük İşlem',
    'stats.migrate': 'Ana Ağ Geçiş İstatistikleri',
    'search.placeholder': 'Ara...',
    'operations.self_transfer': 'Kendi Hesabına Transfer',
    'operations.domain_auction': 'Alan Adı Müzayedesi',
    'operations.claim_claimable_balance': 'π Talep Et',
    'operations.create_account': 'Hesap Oluştur',
    'operations.payment': 'Ödeme',
    'operations.path_payment_strict_receive': 'Sıkı Alım Yolu ile Ödeme',
    'operations.path_payment_strict_send': 'Sıkı Gönderim Yolu ile Ödeme',
    'operations.manage_sell_offer': 'Satış Teklifini Yönet',
    'operations.create_passive_sell_offer': 'Pasif Satış Teklifi Oluştur',
    'operations.set_options': 'Seçenekleri Ayarla',
    'operations.change_trust': 'Güveni Değiştir',
    'operations.allow_trust': 'Güvene İzin Ver',
    'operations.account_merge': 'Hesap Birleştirme',
    'operations.inflation': 'Enflasyon',
    'operations.manage_data': 'Verileri Yönet',
    'operations.bump_sequence': 'Sıralamayı Artır',
    'operations.manage_buy_offer': 'Alım Teklifini Yönet',
    'operations.create_passive_buy_offer': 'Pasif Alım Teklifi Oluştur',
    'operations.create_claimable_balance': 'Talep Edilebilir Bakiye Oluştur',
    'operations.claim_claimable_balance_atom': 'Talep Edilebilir Bakiyeyi Talep Et',
    'operations.deposit': 'Yatır',
    'operations.withdraw': 'Çek',
    'operations.pay': 'Öde',
    'operations.to': 'Alıcı',
    'operations.from': 'Gönderen',
    'operations.claimant': 'Talep Sahibi',
    'operations.with_starting_balance': 'Başlangıç Bakiyesi Dahil',
    'operations.claim': 'Talep Et',
    'operations.heading': 'Pi Ağ Blok Zincirindeki En Son Operasyonları Keşfedin',
    'operations.title': 'Pi Ağındaki En Son Operasyonlar',
    'operations.description': 'Pi Ağ blok zincirindeki en son operasyonları keşfedin.',
    'operations.source_account': 'Kaynak Hesap',
    'operations.operation': 'Operasyon',
    'operations.amount': 'Miktar',
    'operations.tx': 'İşlem',
    'operations.time': 'Zaman',
    'pagination.previous': 'Önceki',
    'pagination.next': 'Sonraki',
    'pagination.page': 'Sayfa',
    'account.title': 'Hesap {{address}} - Pi Ağ Tarayıcısı',
    'account.heading': 'Hesap Detayları',
    'account.heading_with_address': 'Hesap {{address}}',
    'account.description': 'Pi Ağ üzerindeki {{address}} hesabının detayları.',
    'account.loading': 'Hesap detayları yükleniyor...',
    'account.not_found': 'Hesap bulunamadı.',
    'account.scam_warning_title': 'Dolandırıcılık Uyarısı',
    'account.scam_warning_description': 'Topluluk raporlarına göre, bu cüzdan adresi güvenli değil olarak işaretlenmiştir. Dolandırıcılık, özel anahtar ihlali veya yetkisiz erişim ile ilişkili olabilir. İşlem yapmadan önce dikkatli olun.',
    'account.overview': 'Genel Bakış',
    'account.available_balance': 'Kullanılabilir Bakiye',
    'account.last_modified_time': 'Son Değişiklik Zamanı',
    'account.locking': 'Kilitli',
    'account.total_locking': 'Toplam Kilitlenme ({{count}} öğe)',
    'account.next_unlock_time': 'Sonraki Kilidin Açılma Zamanı',
    'account.claimable': 'Talep Edilebilir',
    'account.amount': 'Miktar',
    'account.number_of_items': 'Öğe Sayısı',
    'account.over_100_items': "100'den Fazla Öğe",
    'account.tx_hash': "İşlem Hash'i",
    'account.operation_count': 'Operasyon Sayısı',
    'account.fee': 'Ücret',
    'account.created_at': 'Oluşturulma Zamanı',
    'account.account': 'Hesap',
    'account.effect': 'Etkisi',
    'account.sponsor': 'Sponsor',
    'account.predicate': 'Koşul',
    'account.create_time': 'Oluşturulma Zamanı',
    'account.latest_100_claimable': 'En Son 100 Talep Edilebilir Bakiye',
    'account.tabs.operations': 'Operasyonlar',
    'account.tabs.transactions': 'İşlemler',
    'account.tabs.effects': 'Etkiler',
    'account.tabs.claimable_balances': 'Talep Edilebilir Bakiyeler',
    'effects.account_credited': 'Hesap Alacaklandırıldı',
    'effects.account_debited': 'Hesap Borçlandırıldı',
    'effects.account_created': 'Hesap Oluşturuldu',
    'effects.claimable_balance_created': 'Talep Edilebilir Bakiye Oluşturuldu',
    'effects.claimable_balance_claimed': 'Talep Edilebilir Bakiye Talep Edildi',
    'effects.claimable_balance_claimant_created': 'Talep Edilebilir Bakiye Talep Sahibi Oluşturuldu',
    'effects.account_removed': 'Hesap Silindi',
    'effects.account_thresholds_updated': 'Hesap Eşik Değerleri Güncellendi',
    'effects.account_home_domain_updated': 'Hesap Ana Domaini Güncellendi',
    'effects.account_flags_updated': 'Hesap Bayrakları Güncellendi',
    'effects.account_inflation_destination_updated': 'Hesap Enflasyon Hedefi Güncellendi',
    'effects.signer_created': 'İmza Yetkilisi Oluşturuldu',
    'effects.signer_removed': 'İmza Yetkilisi Kaldırıldı',
    'effects.signer_updated': 'İmza Yetkilisi Güncellendi',
    'effects.trustline_removed': 'Güven Hattı Kaldırıldı',
    'effects.trustline_updated': 'Güven Hattı Güncellendi',
    'effects.trustline_authorized': 'Güven Hattı Yetkilendirildi',
    'effects.trustline_deauthorized': 'Güven Hattı Yetkilendirmesi Kaldırıldı',
    'effects.offer_created': 'Teklif Oluşturuldu',
    'effects.offer_removed': 'Teklif Kaldırıldı',
    'effects.offer_updated': 'Teklif Güncellendi',
    'effects.trade': 'Ticaret Gerçekleşti',
    'effects.data_created': 'Veri Oluşturuldu',
    'effects.data_removed': 'Veri Silindi',
    'effects.data_updated': 'Veri Güncellendi',
    'effects.sequence_bumped': 'Sıra Artırıldı',
    'effects.liquidity_pool_created': 'Likidite Havuzu Oluşturuldu',
    'effects.liquidity_pool_removed': 'Likidite Havuzu Kaldırıldı',
    'effects.liquidity_pool_deposited': 'Likidite Havuzuna Para Yatırıldı',
    'effects.liquidity_pool_withdrew': 'Likidite Havuzundan Para Çekildi',
    'effects.liquidity_pool_trade': 'Likidite Havuzu Ticareti',
    'effects.liquidity_pool_revoked': 'Likidite Havuzu İptal Edildi',
    'effects.contract_credited': 'Sözleşme Alacaklandırıldı',
    'effects.contract_debited': 'Sözleşme Borçlandırıldı',
    'effects.claimable_balance_sponsorship_removed': 'Talep Edilebilir Bakiye Sponsorluğu Kaldırıldı',
    'account_stats.heading': 'Pi Hesap İstatistikleri - Bakiye Dağılımı ve En Üst Hesaplar',
    'account_stats.title': 'Pi Hesap İstatistikleri - Bakiye Dağılımı ve En Üst Hesaplar',
    'account_stats.description': 'Pi ağındaki en zengin Pi hesaplarını ve genel bakiye dağılımını görün.',
    'account_stats.intro_text': 'Tüm hesaplardaki Pi dağılımını keşfedin ve en üst Pi sahiplerini görün.',
    'account_stats.distribution_chart_title': 'Pi Sahip Dağılımı',
    'account_stats.categories_title': 'Dağılım Kategorileri',
    'account_stats.top_accounts_title': 'En Üst Pi Hesapları',
    'account_stats.accounts': 'hesaplar',
    'account_stats.of_total': 'toplamın',
    'account_stats.table.category': 'Kategori',
    'account_stats.table.balance_range': 'Bakiye Aralığı',
    'account_stats.table.usd_value': 'USD Değeri',
    'account_stats.table.accounts': 'Hesap Sayısı',
    'account_stats.table.percentage': 'Toplam Yüzdesi',
    'account_stats.table.total': 'Toplam',
    'account_stats.table.rank': 'Sıra',
    'account_stats.table.account': 'Hesap',
    'account_stats.table.balance': 'Bakiye',
    'account_stats.table.value': 'Değer',
    'account_stats.table.supply_percentage': 'Toplam Arz Yüzdesi',
    'account_stats.categories.whales': 'Balinalar',
    'account_stats.categories.sharks': 'Köpekbalıkları',
    'account_stats.categories.dolphins': 'Yunuslar',
    'account_stats.categories.tunas': 'Ton balıkları',
    'account_stats.categories.fish': 'Balıklar',
    'account_stats.categories.shrimps': 'Karidesler',
    'account_stats.categories.plankton': 'Plankton',
    'account_stats.categories.microbes': 'Mikroorganizmalar',
    'number.billion_short': 'Milyar',
    'number.million_short': 'Milyon',
    'number.thousand_short': 'Bin',
    'common.loading': 'Yükleniyor...',
    'common.sponsored': 'Sponsorlu',
    'common.ad': 'Reklam',
    'common.ad_not_available': 'Bölgenizde sponsorlu içerik mevcut değil',
    'blocks.heading': 'Pi Ağ Blok Zincirindeki En Son Blokları Keşfedin',
    'blocks.title': 'Pi Ağındaki En Son Bloklar',
    'blocks.description': 'Pi ağ blok zincirindeki en son blokları keşfedin.',
    'blocks.sequence': 'Sıra',
    'blocks.hash': 'Hash',
    'blocks.transactions': 'İşlemler',
    'blocks.operations': 'Operasyonlar',
    'blocks.time': 'Zaman',
    'blocks.successful': 'Başarılı',
    'blocks.failed': 'Başarısız',
    'block.title': 'Blok #{{sequence}} - Pi Ağ Tarayıcısı',
    'block.heading': 'Blok #{{sequence}}',
    'block.description': 'Pi ağ blok zincirindeki Blok #{{sequence}} detayları.',
    'block.loading': 'Blok detayları yükleniyor...',
    'block.not_found': 'Blok bulunamadı.',
    'block.information': 'Blok Bilgisi',
    'block.hash': 'Hash',
    'block.previous_hash': 'Önceki Hash',
    'block.sequence': 'Sıra',
    'block.time': 'Zaman',
    'block.total_coins': 'Toplam Coin',
    'block.fee_pool': 'Ücret Havuzu',
    'block.base_fee': 'Temel Ücret',
    'block.base_reserve': 'Temel Rezerv',
    'block.protocol_version': 'Protokol Sürümü',
    'block.tx_hash': "İşlem Hash'i",
    'block.operation_count': 'Operasyon Sayısı',
    'block.fee': 'Ücret',
    'block.created_at': 'Oluşturulma Zamanı',
    'block.tabs.transactions': 'İşlemler',
    'block.tabs.operations': 'Operasyonlar',
    'block.tabs.effects': 'Etkiler',
    'cex.heading': 'CEX ve Çekirdek Takım Hesap İstatistikleri',
    'cex.title': 'Pi Ağındaki CEX ve Çekirdek Takım Hesapları',
    'cex.description': 'Pi ağ blok zincirindeki CEX ve çekirdek takım hesaplarını keşfedin.',
    'cex.wallet_balances': 'CEX Cüzdan Bakiyeleri',
    'cex.core_team_wallets': 'Pi Çekirdek Takım Cüzdanları',
    'cex.cmc_ranking': 'CMC Sıralaması',
    'cex.exchange': 'Borsa',
    'cex.chart_link': 'Grafik Bağlantısı',
    'cex.signup_link': 'Kayıt Bağlantısı',
    'cex.wallet_address': 'Cüzdan Adresi',
    'cex.balance_pi': 'Bakiye (Pi)',
    'cex.balance_usd': 'Bakiye (USD)',
    'cex.chart': 'Grafik',
    'cex.signup': 'Kayıt Ol',
    'cex.total': 'Toplam',
    'cex.note': 'Not',
    'cex.pi_foundation': 'Pi Vakfı',
    'cex.total_in': 'Toplam Giriş (son 24 saat)',
    'cex.total_out': 'Toplam Çıkış (son 24 saat)',
    'cex.net_difference': 'Net Akış (son 24 saat)',
    'cex.flow_data_updated': 'Veriler her 30 dakikada bir güncellenir',
    'cex.actions': 'İşlemler',
    'cex.filter_transactions_tooltip': 'Bu adres için işlemleri filtrele',
    'cex.filter_txs_button': 'İşlemleri Filtrele',
    'pct.nav': 'Çekirdek Takım',
    'cex_monitor.nav': 'Borsalar',
    'pct.title': 'Çekirdek Takım Cüzdan Takibi',
    'pct.subtitle': 'Sadece doğrulanmış bakiye değişimleri gösterilir.',
    'pct.tab_wallets': 'Cüzdanlar',
    'pct.tab_updates': 'Güncellemeler',
    'pct.tab_history': 'Geçmiş',
    'pct.stat_tracked': 'İzlenen cüzdan',
    'pct.stat_starting': 'Başlangıç bakiyesi',
    'pct.stat_current': 'Güncel bakiye',
    'pct.stat_changes': 'Onaylı değişiklik',
    'pct.stat_total_out': 'Toplam çıkış',
    'pct.stat_24h': '24s net değişim',
    'pct.section_wallets': 'Çekirdek takım cüzdan listesi',
    'pct.section_updates': 'Son değişimler (7 gün)',
    'pct.section_history': 'En yeni değişimler',
    'pct.latest_check': 'Son kontrol:',
    'pct.scan_running': 'tarama sürüyor',
    'pct.prev': 'Önceki',
    'pct.next': 'Sonraki',
    'pct.wallets_index': 'cüzdan',
    'pct.footer_note': 'Explorer bağlantıları resmi Pi blok gezginini açar.',
    'pct.col_wallet': 'Cüzdan',
    'pct.col_old': 'Eski bakiye',
    'pct.col_new': 'Yeni bakiye',
    'pct.col_change': 'Değişim',
    'pct.col_detected': 'Algılandı',
    'pct.col_ledger': 'Ledger',
    'pct.no_changes': 'Henüz kayıt yok, lütfen sonra tekrar bakın.',
    'pct.loading': 'Yükleniyor…',
    'pct.load_more': 'Daha fazla',
    'pct.summary_error': 'Özet sunucudan alınamadı.',
    'cex_monitor.title': 'Borsa Cüzdan Takibi',
    'cex_monitor.subtitle': 'Doğrulanmış bakiye değişimleri olan borsa cüzdanları.',
    'cex_monitor.tab_wallets': 'Cüzdanlar',
    'cex_monitor.tab_updates': 'Güncellemeler',
    'cex_monitor.tab_history': 'Geçmiş',
    'cex_monitor.stat_tracked': 'İzlenen cüzdan',
    'cex_monitor.stat_starting': 'Başlangıç bakiyesi',
    'cex_monitor.stat_current': 'Güncel bakiye',
    'cex_monitor.stat_changes': 'Onaylı değişiklik',
    'cex_monitor.stat_total_out': 'Toplam çıkış',
    'cex_monitor.stat_24h': '24s net değişim',
    'cex_monitor.section_wallets': 'Borsa cüzdan listesi',
    'cex_monitor.section_updates': 'Son değişimler (7 gün)',
    'cex_monitor.section_history': 'En yeni onaylı değişimler',
    'cex_monitor.latest_check': 'Son kontrol:',
    'cex_monitor.scan_running': 'tarama sürüyor',
    'cex_monitor.prev': 'Önceki',
    'cex_monitor.next': 'Sonraki',
    'cex_monitor.wallets_index': 'cüzdan',
    'cex_monitor.footer_note': 'Explorer bağlantıları resmi Pi blok gezginini açar.',
    'cex_monitor.col_wallet': 'Cüzdan',
    'cex_monitor.col_old': 'Eski bakiye',
    'cex_monitor.col_new': 'Yeni bakiye',
    'cex_monitor.col_change': 'Değişim',
    'cex_monitor.col_detected': 'Algılandı',
    'cex_monitor.col_ledger': 'Ledger',
    'cex_monitor.no_changes': 'Henüz onaylı değişiklik yok. Daha sonra tekrar kontrol edin.',
    'cex_monitor.loading': 'Yükleniyor…',
    'cex_monitor.load_more': 'Daha fazla',
    'cex_monitor.summary_error': 'CEX özeti sunucudan alınamadı.',
    'contact.heading': 'Bize Ulaşın',
    'contact.title': 'PiScan ile İletişime Geçin',
    'contact.description': 'Herhangi bir sorunuz veya geri bildiriminiz varsa, lütfen PiScan ile iletişime geçin.',
    'contact.intro_text': 'Sorularınız varsa, aşağıdaki yolla bizimle iletişime geçin',
    'contact.success_message': 'Bize ulaştığınız için teşekkürler! En kısa sürede size dönüş yapacağız.',
    'contact.form.name': 'Adınız',
    'contact.form.email': 'E-posta Adresiniz',
    'contact.form.message': 'Mesaj',
    'contact.form.submit': 'Mesaj Gönder',
    'home.heading': 'Pi Ağ İşlemlerini, Cüzdanlarını ve İstatistiklerini Keşfedin',
    'home.title': 'Pi Ağ İşlemlerini, Cüzdanlarını ve İstatistiklerini Keşfedin',
    'home.description': 'Pi ağ işlemlerini, cüzdanlarını ve istatistiklerini keşfedin',
    'home.market_cap': 'Piyasa Değeri',
    'home.price': 'Fiyat',
    'home.24h_change': '24 Saat Değişim',
    'home.pi_supply': 'Pi Arzı',
    'home.circulating': 'Dolaşımdaki',
    'home.locked': 'Kilitli',
    'home.cex_balance_total': 'CEX Bakiyesi (Toplam)',
    'home.view_all': 'Tümünü Gör',
    'home.network_stats': 'Ağ İstatistikleri',
    'home.blocks': 'Bloklar',
    'home.tps': 'TPS',
    'home.latest_transactions': 'En Son İşlemler',
    'home.signature': 'İmza',
    'home.time': 'Zaman',
    'home.block': 'Blok',
    'home.ops': 'Operasyonlar',
    'home.latest_operations': 'En Son Operasyonlar',
    'home.source_account': 'Kaynak Hesap',
    'home.operation': 'Operasyon',
    'home.amount': 'Miktar',
    'home.tx': 'İşlem',
    'nodes.heading': 'Pi Ağ Düğümler Haritası ve Ağ İstatistikleri',
    'nodes.title': 'Pi Ağ Düğümleri ve Doğrulayıcılar',
    'nodes.description': 'Pi ağ düğümlerini, doğrulayıcıları ve ağ topolojisini keşfedin. Düğümlerin küresel dağılımını ve bağlantılarını görün.',
    'nodes.active_nodes': 'Aktif Düğümler',
    'nodes.validators': 'Doğrulayıcılar',
    'nodes.known_peers': 'Bilinen Eşler',
    'nodes.disconnected_nodes': 'Bağlantısı Kesilmiş Düğümler',
    'nodes.network_graph': 'Ağ Grafiği',
    'nodes.node_types': 'Düğüm Türleri',
    'nodes.validator': 'Doğrulayıcı',
    'nodes.watcher': 'İzleyici',
    'nodes.disconnected_private': 'Bağlantısı Kesilmiş/Özel',
    'nodes.click_to_highlight': 'Bağlantıları vurgulamak için düğüme tıklayın',
    'nodes.global_distribution': 'Küresel Dağılım',
    'nodes.mapped_nodes': 'Haritalanmış Düğümler',
    'nodes.node_details': 'Düğüm Detayları',
    'nodes.nodes': 'Düğümler',
    'nodes.address': 'Adres',
    'nodes.type': 'Tür',
    'nodes.location': 'Konum',
    'nodes.isp': 'İnternet Servis Sağlayıcısı',
    'nodes.version': 'Sürüm',
    'nodes.trust': 'Güven',
    'nodes.trusted_by': 'Güvenilen',
    'nodes.status': 'Durum',
    'nodes.status.connected': 'Bağlı',
    'nodes.status.disconnected': 'Bağlantısı Kesilmiş',
    'nodes.status.private': 'Özel',
    'nodes.active_quorum_sets': 'Aktif Oy Birliği Setleri',
    'nodes.active': 'Aktif',
    'nodes.quorum_hash': "Oy Birliği Hash'i",
    'nodes.node_id': "Düğüm ID'si",
    'nodes.unknown': 'Bilinmiyor',
    'nodes.core_team': 'Çekirdek Takım',
    'nodes.tooltip.node_id': "Düğüm ID'si",
    'nodes.tooltip.address': 'Adres',
    'nodes.tooltip.type': 'Tür',
    'nodes.tooltip.status': 'Durum',
    'nodes.tooltip.version': 'Sürüm',
    'nodes.tooltip.location': 'Konum',
    'nodes.tooltip.not_accessible': 'Erişilemiyor',
    'nodes.phantom_validators': 'Hayalet Doğrulayıcılar',
    'nodes.country_statistics': 'Ülke İstatistikleri',
    'nodes.city_statistics': 'Şehir İstatistikleri',
    'nodes.online_nodes_only': 'Yalnızca Çevrimiçi Düğümler',
    'nodes.country': 'Ülke',
    'nodes.city': 'Şehir',
    'nodes.connected_nodes': 'Bağlı Düğümler',
    'nodes.no_country_data': 'Ülke verisi bulunamadı',
    'nodes.no_city_data': 'Şehir verisi bulunamadı',
    'nodes_testnet.heading': 'Pi Network Testnet Düğüm İstatistikleri',
    'nodes_testnet.title': 'Pi Network Testnet Düğümleri',
    'nodes_testnet.description': 'Pi Network testnet düğüm istatistiklerini ve küresel dağılımını keşfedin.',
    'nodes_testnet.summary_title': 'Testnet Düğüm Özeti',
    'nodes_testnet.summary_description': 'Pi Network testnet düğümlerinin gerçek zamanlı istatistikleri ve etkinlik seviyeleri.',
    'nodes_testnet.total_peers': 'Toplam Eş',
    'nodes_testnet.active_peers': 'Aktif Eş',
    'nodes_testnet.activity_rate': 'Etkinlik Oranı',
    'nodes_testnet.country_statistics': 'Ülke İstatistikleri',
    'nodes_testnet.city_statistics': 'Şehir İstatistikleri',
    'nodes_testnet.country': 'Ülke',
    'nodes_testnet.city': 'Şehir',
    'nodes_testnet.total_nodes': 'Toplam Düğüm',
    'nodes_testnet.active_nodes': 'Aktif Düğüm',
    'nodes_testnet.active_rate': 'Aktiflik Oranı',
    'report_scam.heading': 'Dolandırıcılık Cüzdanını Bildir',
    'report_scam.title': "PiScan'de Dolandırıcılık Cüzdanını Bildir",
    'report_scam.description': 'Dolandırıcılık veya sahtekarlık faaliyetiyle ilişkili cüzdan adresini bildirin.',
    'report_scam.intro_text': "Dolandırıcılık veya sahtekarlık faaliyetiyle ilişkili şüpheli bir cüzdan adresiyle karşılaştıysanız, lütfen aşağıdaki formu doldurarak bildirin. Ekibimiz gönderinizi inceleyecek ve dolandırıcılık olarak doğrulanırsa, topluluğu uyarmak amacıyla PiScan'de ilgili cüzdanı 'Dolandırıcılık' olarak işaretleyecektir.",
    'report_scam.success_message': 'Bildiriminiz için teşekkürler! Ekibimiz en kısa sürede inceleyecektir.',
    'report_scam.form.wallet_address': 'Cüzdan Adresi',
    'report_scam.form.wallet_placeholder': 'Dolandırıcılık cüzdan adresini girin',
    'report_scam.form.reason': 'Bildirim Nedeni',
    'report_scam.form.reason_placeholder': 'Bu cüzdanın neden dolandırıcılıkla ilişkili olduğuna dair açıklama yapın',
    'report_scam.form.email': 'E-posta Adresiniz (Opsiyonel)',
    'report_scam.form.email_placeholder': 'E-posta adresinizi girin (opsiyonel)',
    'report_scam.form.email_note': 'Daha fazla bilgi için sizinle iletişime geçebiliriz.',
    'report_scam.form.submit': 'Bildirimi Gönder',
    'transaction.title': 'Pi Ağındaki İşlem #{{id}}',
    'transaction.heading': 'İşlem Detayları',
    'transaction.description': 'Pi ağ blok zincirindeki İşlem #{{id}} detayları.',
    'transaction.loading': 'İşlem detayları yükleniyor...',
    'transaction.not_found': 'İşlem bulunamadı.',
    'transaction.hash': 'Hash',
    'transaction.ledger_block': 'Defter (Blok)',
    'transaction.result': 'Sonuç',
    'transaction.source_account': 'Kaynak Hesap',
    'transaction.fee_account': 'Ücret Hesabı',
    'transaction.fee': 'Ücret',
    'transaction.operation_count': 'Operasyon Sayısı',
    'transaction.summary': 'Özet',
    'transaction.operations': 'Operasyonlar',
    'transaction.effects': 'Etkiler',
    'transaction.account': 'Hesap',
    'transaction.operation': 'Operasyon',
    'transaction.effect': 'Etki',
    'transaction.amount': 'Miktar',
    'transaction.successful': 'Başarılı',
    'transaction.failed': 'Başarısız',
    'transaction.loading_details': 'İşlem detayları yükleniyor...',
    'transaction.with_operations': '{{count}} adet operasyon içeren işlem',
    'transaction.core_team_distributed': 'Pi Çekirdek Takım tarafından dağıtıldı',
    'transaction.to': 'Alıcı',
    'transaction.accounts': 'Hesaplar',
    'transaction.locked_for_days': ', {{days}} gün kilitli',
    'transaction.locked_range_days': ', kilit süresi {{minDays}} günden {{maxDays}} güne kadar değişiyor',
    'transaction.created_at': 'Oluşturulma Zamanı',
    'unlock_stats.heading': 'Pi Kilidini Açma İstatistikleri - Önümüzdeki 30 Gün',
    'unlock_stats.title': 'Pi Kilidini Açma İstatistikleri - Önümüzdeki 30 Gün',
    'unlock_stats.description': 'Önümüzdeki 30 gün için Pi kripto paranın kilidini açma tahminlerini görün.',
    'unlock_stats.intro_text': 'Önümüzdeki 30 gündeki Pi kilidinin açılması, talep edilebilir bakiyeye dayanmaktadır – bu bakiye kullanıcı tarafından kilitlenmiş veya Pi Çekirdek Takım tarafından dağıtılmış olabilir. Henüz talep edilebilir bakiyeye dahil olmayan yayınlanmamış Pi takip edilemez. Lütfen düzenli olarak güncellemeleri kontrol edin. Tüm zamanlar UTC\'dir.',
    'unlock_stats.today_note': 'Bugünkü kilidini açma miktarı, şuan itibariyle gün sonuna (UTC) kadar açılacak kalan Pi\'yi temsil eder.',
    'unlock_stats.updated_at': 'Veri güncellendi:',
    'unlock_stats.unknown': 'Bilinmiyor',
    'unlock_stats.total_locked': 'Toplam Kilitli Pi',
    'unlock_stats.total_next_30': 'Önümüzdeki 30 Gün İçin Toplam Kilidini Açma',
    'unlock_stats.of_total_locked': 'toplam kilitli miktarın',
    'unlock_stats.avg_daily': 'Ortalama Günlük Kilidini Açma',
    'unlock_stats.per_day': 'günlük',
    'unlock_stats.highest_day': 'En Yüksek Kilidini Açma Günü',
    'unlock_stats.on': 'tarihinde',
    'unlock_stats.chart_title': 'Pi Kilidini Açma Grafiği - Önümüzdeki 30 Gün',
    'unlock_stats.data_table': 'Kilidini Açma Veri Tablosu',
    'unlock_stats.date': 'Tarih',
    'unlock_stats.amount': 'Miktar',
    'unlock_stats.value': 'Değer',
    'unlock_stats.pi_unlock': 'Pi Kilidini Açma',
    'unlock_stats.y_axis_label': 'Pi Kilidini Açma (milyon cinsinden)',
    'unlock_stats.monthly_heading': 'Aylık Pi Kilit Açma İstatistikleri',
    'unlock_stats.monthly_title': 'Aylık Pi Kilit Açma İstatistikleri',
    'unlock_stats.total_next_12': 'Önümüzdeki 12 Ay İçin Toplam Kilidini Açma',
    'unlock_stats.monthly_description': 'Aylara göre Pi kripto para kilit açma istatistiklerini görüntüleyin',
    'unlock_stats.monthly_intro_text': 'Aylık Pi kripto para kilit açma istatistiklerini görüntüleyin.',
    'unlock_stats.monthly_note': 'İstatistikler uygun kilit açma taleplerine dayanmaktadır.',
    'unlock_stats.monthly_chart_title': 'Aylık Pi Kilit Açma İstatistikleri Grafiği',
    'unlock_stats.total_forecast': 'Toplam İstatistik',
    'unlock_stats.monthly_data_table': 'Aylık Kilit Açma Verileri',
    'unlock_stats.total_locking': 'Toplam Kilitlenen Miktar',
    'unlock_stats.avg_monthly': 'Aylık Ortalama',
    'unlock_stats.highest_month': 'En Yüksek Ay',
    'unlock_stats.per_month': 'ay başına',
    'unlock_stats.in': 'içinde',
    'unlock_stats.month': 'Ay',
    'unlock_stats.view_daily': 'Günlük Kilit Açma İstatistiklerini Görüntüle',
    'unlock_stats.view_monthly': 'Aylık Kilit Açma İstatistiklerini Görüntüle',
    'common.loading_error': 'Veriler yüklenirken bir hata oluştu. Lütfen daha sonra tekrar deneyin.',
    'settings.aria_label': 'Ayarları aç',
    'settings.language': 'Dil',
    'settings.appearance': 'Görünüm',
    'settings.dark_mode': 'Karanlık mod',
    'settings.light': 'Açık',
    'settings.dark': 'Koyu',
    'transactios.heading': 'Pi Ağı Blok Zincirindeki En Son İşlemleri Keşfedin',
    'transactions.title': 'Pi Ağındaki En Son İşlemler',
    'transactions.description': 'Pi ağ blok zincirindeki en son işlemleri keşfedin.',
    'domain_auction_stats.heading': 'Pi Alan Adı Açık Artırma İstatistikleri',
    'domain_auction_stats.title': 'Pi Alan Adı Açık Artırma İstatistikleri | Pi Ağ İstatistikleri',
    'domain_auction_stats.description': 'Pi Ağı alan adı açık artırmalarının analizini gösterir, farklı fiyat aralıklarındaki teklif dağılımını ve şimdiye kadar teklif edilen toplam Pi miktarını sunar.',
    'domain_auction_stats.intro_text': 'Bu sayfa, Pi alan adı açık artırmalarına ilişkin analizler sunar ve farklı fiyat aralıklarındaki teklif dağılımını vurgular.',
    'domain_auction_stats.last_updated': 'Son Güncelleme',
    'domain_auction_stats.summary_title': 'Açık Artırma Teklif Özeti',
    'domain_auction_stats.total_bids': 'Toplam Teklif Sayısı',
    'domain_auction_stats.total_pi_bid': 'Şimdiye Kadar Teklif Edilen Toplam Pi',
    'domain_auction_stats.estimated_value': 'Tahmini Değer (USD)',
    'domain_auction_stats.pi_price': 'Güncel Pi Fiyatı',
    'domain_auction_stats.distribution_title': 'Teklif Dağılımı',
    'domain_auction_stats.chart_title': 'Teklif Fiyat Dağılımı',
    'domain_auction_stats.details_title': 'Canlı Teklif Ayrıntıları',
    'domain_auction_stats.bids': 'teklifler',
    'domain_auction_stats.of_total': 'toplam teklifler içinde',
    'domain_auction_stats.bid_count': 'Teklif Sayısı',
    'domain_auction_stats.ranges.low': 'Düşük Teklifler',
    'domain_auction_stats.ranges.medium': 'Standart Teklifler',
    'domain_auction_stats.ranges.high': 'Premium Teklifler',
    'domain_auction_stats.ranges.premium': 'Lüks Teklifler',
    'domain_auction_stats.ranges.elite': 'Elit Teklifler',
    'domain_auction_stats.table.price_range': 'Teklif Fiyat Aralığı',
    'domain_auction_stats.table.bid_count': 'Teklif Sayısı',
    'domain_auction_stats.table.percentage': 'Yüzde',
    'domain_auction_stats.table.total': 'Toplam Teklifler',
    'domain_auction_stats.highest_bid': 'En Yüksek Teklif',
    'domain_auction_stats.top_bids_title': 'En Yüksek Teklifler',
    'domain_auction_stats.table.account': 'Hesap',
    'domain_auction_stats.table.bid_amount': 'Teklif Miktarı',
    'domain_auction_stats.table.usd_value': 'USD Değeri',
    'largest_tx.heading': 'En Büyük Pi İşlemleri (Son 24 Saat)',
    'largest_tx.title': 'Son 24 Saat İçindeki En Büyük Pi İşlemleri - PiScan',
    'largest_tx.description': 'Son 24 saat içinde Pi Network blok zincirindeki en büyük Pi işlemlerini keşfedin.',
    'largest_tx.list_heading': 'Miktara Göre En Büyük İşlemler (Son 24 Saat)',
    'largest_tx.rank': 'Sıralama',
    'largest_tx.transaction': 'İşlem',
    'largest_tx.account': 'Hesap',
    'largest_tx.amount': 'Miktar (π)',
    'largest_tx.date': 'Tarih & Saat',
    'largest_tx.no_data': 'Son 24 saat içinde işlem verisi bulunmamaktadır.',
    'largest_tx.fetch_error': 'İşlem verisi alınamadı.',
    'largest_tx.loading': 'En büyük işlemler yükleniyor...',
    'largest_tx.largest_amount': 'En Büyük İşlem Miktarı (Son 24 Saat)',
    'largest_tx.latest_large_tx': 'En Son Büyük İşlem (Son 24 Saat)',
    'largest_tx.total_value': 'Toplam Değer (İlk 100 İşlem, Son 24 Saat)',
    'migrate_stats.heading': 'Pi Geçiş İstatistikleri',
    'migrate_stats.title': 'Pi Ana Ağa Geçiş İstatistikleri - PiScan',
    'migrate_stats.description': 'Son günlerde Pi\'nin ana ağa geçişine dair günlük istatistikleri takip edin.',
    'migrate_stats.last_updated': 'Son Güncelleme',
    'migrate_stats.daily_migration': 'Günlük Geçiş Hacmi',
    'migrate_stats.daily_stats': 'Güne Göre Geçiş İstatistikleri',
    'migrate_stats.loading': 'Geçiş istatistikleri yükleniyor...',
    'migrate_stats.no_data': 'Geçiş verisi bulunmamaktadır.',
    'migrate_stats.fetch_error': 'Geçiş verisi alınamadı.',
    'migrate_stats.date': 'Tarih',
    'migrate_stats.amount': 'Miktar (π)',
    'migrate_stats.percentage': 'Yüzde (%)',
    'migrate_stats.total': 'Toplam',
    'migrate_stats.pi_migrated': 'Toplam Geçirilen Pi',
    'migrate_stats.date_label': 'Tarih: {{date}}',
    'migrate_stats.usd_value': 'USD Değeri',
    'migrate_stats.at_price': 'mevcut fiyat üzerinden',
    'migrate_stats.current_price_note': 'USD değerleri mevcut Pi fiyatı {{price}} π başına hesaplanmıştır.',
    'transactions_filter.heading': 'İşlemleri Filtrele',
    'transactions_filter.title': 'İşlemleri Filtrele | Pi Scan',
    'transactions_filter.description': 'Adres, tutar ve diğer kriterlere göre Pi Network işlemlerini filtreleyin ve arayın.',
    'transactions_filter.address_required_error': 'Adres zorunludur.',
    'transactions_filter.min_amount_required_error': 'En az tutar girilmelidir.',
    'transactions_filter.amount_too_low_error': 'Tutar 10.000\'dan az olamaz.',
    'transactions_filter.min_exceeds_max_error': 'En az tutar, en fazla tutarı aşamaz.',
    'transactions_filter.filter_options': 'Filtre Seçenekleri',
    'transactions_filter.address': 'Adres',
    'transactions_filter.address_placeholder': 'Hesap adresini girin',
    'transactions_filter.min_amount': 'En Az Tutar (Pi)',
    'transactions_filter.min_amount_placeholder': 'örn. 10000',
    'transactions_filter.max_amount': 'En Fazla Tutar (Pi)',
    'transactions_filter.max_amount_placeholder': 'örn. 100000',
    'transactions_filter.apply_filters': 'Uygula',
    'transactions_filter.clear': 'Temizle',
    'transactions_filter.no_results': 'Kriterlerinize uygun işlem bulunamadı.',
    'transactions_filter.results': 'Sonuçlar',
    'transactions_filter.table.hash': 'İşlem Hash\'i',
    'transactions_filter.table.time': 'Zaman',
    'transactions_filter.table.from': 'Gönderen',
    'transactions_filter.table.to': 'Alıcı',
    'transactions_filter.table.amount': 'Tutar (Pi)',
    'transactions_filter.apply_filters_prompt': 'Sonuçları görmek için lütfen filtreleri uygulayın.',
    'transactions_filter.table.tx': 'İşlem',
    'transactions_filter.table.detail_button': 'Detayları Gör',
    'transactions_filter.operation_text.payment': '{{from}} adresinden {{to}} adresine {{amount}} Pi ödemesi',
    'transactions_filter.operation_text.unknown': 'Bilinmeyen Operasyon',
    'docs.heading': 'Geliştirici Dokümantasyonu',
    'docs.title': 'Dokümanlar & API - Zyrachain',
    'docs.description': 'Pi Network verilerini uygulamalarınıza entegre etmek için geliştirici dokümantasyonu ve API uç noktaları.',
    'docs.hero_subtitle': 'Pi Network verileriyle harika uygulamalar geliştirin. Kapsamlı API\'lerimiz aracılığıyla gerçek zamanlı blok zinciri bilgilerine, DApp listelerine ve topluluk özelliklerine erişin.',
    'docs.features.real_time': 'Gerçek Zamanlı Veri',
    'docs.features.restful': 'RESTful API\'ler',
    'docs.features.secure': 'Güvenli & Güvenilir',
    'docs.tabs.overview': 'Genel Bakış',
    'docs.tabs.endpoints': 'API Uç Noktaları',
    'docs.tabs.integration': 'Pi Entegrasyonu',
    'docs.tabs.examples': 'Örnekler',
    'docs.tabs.support': 'Destek',
    'docs.blockchain_data.title': 'Blok Zinciri Veri API\'si',
    'docs.blockchain_data.description': 'Gerçek zamanlı Pi Network blok zinciri bilgilerine erişin',
    'docs.blockchain_data.features': [
        'İşlem detayları ve geçmişi',
        'Blok bilgileri ve istatistikleri',
        'Hesap bakiyeleri ve operasyonları',
        'Ağ metrikleri (TPS, arz vb.)'
    ],
    'docs.dapp_directory.title': 'DApp Dizini API\'si',
    'docs.dapp_directory.description': 'Pi Network uygulamalarını keşfedin ve yönetin',
    'docs.dapp_directory.features': [
        'Öne çıkan DApp\'leri keşfedin',
        'Kategorilere göre filtreleyin',
        'Yeni uygulamalar gönderin',
        'Trend olan uygulamaları takip edin'
    ],
    'docs.getting_started.title': 'Başlangıç',
    'docs.getting_started.description': 'API\'lerimizle entegrasyona başlamak için bu adımları izleyin',
    'docs.step1.title': 'API\'nizi Seçin',
    'docs.step1.description': 'Blok zinciri verileri, DApp dizini veya topluluk API\'leri arasından seçim yapın',
    'docs.step2.title': 'API Çağrıları Yapın',
    'docs.step2.description': 'Standart HTTP yöntemleriyle RESTful uç noktalarımızı kullanın',
    'docs.step3.title': 'Harika Uygulamalar Geliştirin',
    'docs.step3.description': 'Kullanıcılarınız için güçlü Pi Network uygulamaları oluşturun',
    'docs.base_url.title': 'Temel URL',
    'docs.base_url.description': 'Tüm API istekleri bu temel URL\'ye yapılmalıdır',
    'docs.base_url.value': 'https://clubhouse-pi.io/api/v1',
    'docs.endpoints.stats.title': 'Blok Zinciri İstatistikleri',
    'docs.endpoints.stats.description': 'Gerçek zamanlı Pi Network istatistiklerini alın',
    'docs.endpoints.stats.method': 'GET',
    'docs.endpoints.stats.path': '/api/v1/stats',
    'docs.endpoints.stats.response': 'TPS, arz ve daha fazlasını içeren ağ istatistiklerini döndürür',
    'docs.endpoints.transactions.title': 'En Son İşlemler',
    'docs.endpoints.transactions.description': 'Ağdaki en son işlemleri alın',
    'docs.endpoints.transactions.method': 'GET',
    'docs.endpoints.transactions.path': '/api/v1/transactions',
    'docs.endpoints.transactions.params': 'limit, cursor, order',
    'docs.endpoints.blocks.title': 'En Son Bloklar',
    'docs.endpoints.blocks.description': 'Ağdaki en son blokları alın',
    'docs.endpoints.blocks.method': 'GET',
    'docs.endpoints.blocks.path': '/api/v1/blocks',
    'docs.endpoints.blocks.params': 'limit, cursor, order',
    'docs.endpoints.account.title': 'Hesap Detayları',
    'docs.endpoints.account.description': 'Detaylı hesap bilgilerini alın',
    'docs.endpoints.account.method': 'GET',
    'docs.endpoints.account.path': '/api/v1/accounts/{address}',
    'docs.endpoints.account.params': 'address (zorunlu)',
    'docs.endpoints.transaction.title': 'İşlem Detayları',
    'docs.endpoints.transaction.description': 'Detaylı işlem bilgilerini alın',
    'docs.endpoints.transaction.method': 'GET',
    'docs.endpoints.transaction.path': '/api/v1/transactions/{hash}',
    'docs.endpoints.transaction.params': 'hash (zorunlu)',
    'docs.integration.title': 'Pi Network Entegrasyonu',
    'docs.integration.description': 'Pi Network kimlik doğrulama ve ödemelerini nasıl entegre edeceğinizi öğrenin',
    'docs.integration.auth.title': 'Kimlik Doğrulama',
    'docs.integration.auth.description': 'Uygulamalarınızda Pi Network kimlik doğrulamasını kullanın',
    'docs.integration.payments.title': 'Ödemeler',
    'docs.integration.payments.description': 'Uygulamalarınızda Pi ödemelerini kabul edin',
    'docs.examples.title': 'Kod Örnekleri',
    'docs.examples.description': 'Yaygın kullanım durumları için kullanıma hazır kod örnekleri',
    'docs.examples.javascript.title': 'JavaScript/Node.js',
    'docs.examples.python.title': 'Python',
    'docs.examples.curl.title': 'cURL',
    'docs.support.title': 'Destek & Kaynaklar',
    'docs.support.description': 'Yardım alın ve ek kaynakları bulun',
    'docs.support.community.title': 'Topluluk',
    'docs.support.community.description': 'Destek ve tartışmalar için geliştirici topluluğumuza katılın',
    'docs.support.documentation.title': 'Dokümantasyon',
    'docs.support.documentation.description': 'Kapsamlı kılavuzlar ve eğitimler',
    'docs.support.api_reference.title': 'API Referansı',
    'docs.support.api_reference.description': 'Eksiksiz API uç noktası dokümantasyonu',
    'terms.heading': 'Hizmet Şartları',
    'terms.title': 'Hizmet Şartları - Zyrachain',
    'terms.description': 'Zyrachain hizmetlerinin ve platformunun kullanımını düzenleyen şartlar ve koşullar.',
    'terms.section1.title': 'Şartların Kabulü',
    'terms.section1.content': 'Zyrachain\'e ("Hizmet") erişerek ve kullanarak, bu sözleşmenin şartlarını ve hükümlerini kabul etmiş ve bunlara bağlı kalmayı taahhüt etmiş olursunuz. Yukarıdakilere uymayı kabul etmiyorsanız, lütfen bu hizmeti kullanmayın.',
    'terms.section2.title': 'Kullanım Lisansı',
    'terms.section2.content': 'Zyrachain\'in web sitesindeki materyallerin (bilgi veya yazılım) bir kopyasının yalnızca kişisel, ticari olmayan geçici görüntüleme amacıyla indirilmesine izin verilir. Bu bir lisans verilmesidir, mülkiyet devri değildir ve bu lisans kapsamında: materyalleri değiştiremez veya kopyalayamazsınız; materyalleri herhangi bir ticari amaç veya kamuya açık gösterim için kullanamazsınız; Zyrachain\'in web sitesindeki herhangi bir yazılımı tersine mühendislik yapmaya çalışamazsınız; materyallerden herhangi bir telif hakkı veya diğer mülkiyet bildirimlerini kaldıramazsınız; veya materyalleri başka bir kişiye aktaramaz veya materyalleri başka bir sunucuda "yansıtamazsınız".',
    'terms.section3.title': 'Sorumluluk Reddi',
    'terms.section3.content': 'Zyrachain\'in web sitesindeki materyaller "olduğu gibi" esasına göre sağlanmaktadır. Zyrachain, açık veya zımni hiçbir garanti vermez ve ticari elverişlilik, belirli bir amaca uygunluk veya fikri mülkiyet haklarının ihlal edilmemesi veya diğer hak ihlalleri dahil ancak bunlarla sınırlı olmamak üzere, zımni garantiler de dahil olmak üzere tüm diğer garantileri reddeder.',
    'terms.section4.title': 'Sınırlamalar',
    'terms.section4.content': 'Hiçbir durumda Zyrachain veya tedarikçileri, Zyrachain\'in web sitesindeki materyallerin kullanımından veya kullanılamamasından kaynaklanan herhangi bir zarardan (veri veya kar kaybı veya iş kesintisinden kaynaklanan zararlar dahil ancak bunlarla sınırlı olmamak üzere), Zyrachain veya Zyrachain yetkili temsilcisi bu tür bir zararın olasılığı hakkında sözlü veya yazılı olarak bilgilendirilmiş olsa bile sorumlu tutulamaz.',
    'terms.section5.title': 'Materyallerin Doğruluğu',
    'terms.section5.content': 'Zyrachain\'in web sitesinde görünen materyaller teknik, yazım veya fotoğraf hataları içerebilir. Zyrachain, web sitesindeki materyallerin hiçbirinin doğru, eksiksiz veya güncel olduğunu garanti etmez. Zyrachain, web sitesinde yer alan materyallerde herhangi bir zamanda bildirimde bulunmaksızın değişiklik yapabilir.',
    'terms.section6.title': 'Bağlantılar',
    'terms.section6.content': 'Zyrachain, web sitesine bağlı tüm siteleri incelememiştir ve bu tür bağlı sitelerin içeriğinden sorumlu değildir. Herhangi bir bağlantının dahil edilmesi, Zyrachain tarafından sitenin onaylandığı anlamına gelmez. Bu tür bağlı web sitelerinin kullanımı kullanıcının kendi riski altındadır.',
    'terms.section7.title': 'Değişiklikler',
    'terms.section7.content': 'Zyrachain, web sitesi için bu hizmet şartlarını herhangi bir zamanda bildirimde bulunmaksızın revize edebilir. Bu web sitesini kullanarak, Hizmet Şartları\'nın o zamanki güncel sürümüne bağlı kalmayı kabul etmiş olursunuz.',
    'terms.section8.title': 'Yürürlükteki Hukuk',
    'terms.section8.content': 'Bu şartlar ve koşullar, yasalara uygun olarak yönetilir ve yorumlanır ve ilgili bölgedeki mahkemelerin münhasır yargı yetkisine geri dönülemez şekilde tabi olursunuz.',
    'terms.contact.title': 'İletişim Bilgileri',
    'terms.contact.content': 'Bu Hizmet Şartları hakkında sorularınız varsa, lütfen bizimle iletişime geçin:',
    'terms.contact.email': 'zyrachains@gmail.com',
    'contact.email': 'zyrachains@gmail.com',
    'privacy.heading': 'Gizlilik Politikası',
    'privacy.title': 'Gizlilik Politikası - Zyrachain Pi Network Ekosistem Merkezi',
    'privacy.description': 'Kişisel bilgilerinizi nasıl topladığımız, kullandığımız ve koruduğumuz.',
    'privacy.section1.title': 'Topladığımız Bilgiler',
    'privacy.section1.content': 'Hesap oluşturduğunuzda, bizimle iletişime geçtiğinizde veya hizmetlerimizi kullandığınızda bize doğrudan sağladığınız bilgileri toplarız. Bu, adınızı, e-posta adresinizi, cüzdan adreslerinizi ve sağlamayı seçtiğiniz diğer bilgileri içerebilir. Ayrıca, IP adresiniz, tarayıcı türünüz, işletim sisteminiz ve kullanım şekilleriniz dahil olmak üzere hizmetlerimizi kullandığınızda otomatik olarak belirli bilgileri toplarız.',
    'privacy.section2.title': 'Bilgilerinizi Nasıl Kullanıyoruz',
    'privacy.section2.content': 'Topladığımız bilgileri hizmetlerimizi sağlamak, sürdürmek ve iyileştirmek, sizinle iletişim kurmak, yeni özellikler geliştirmek ve kullanıcılarımızı ve kamuoyunu korumak için kullanırız. Ayrıca bilgilerinizi size teknik bildirimler, güncellemeler, güvenlik uyarıları ve destek mesajları göndermek için kullanabiliriz.',
    'privacy.section3.title': 'Bilgi Paylaşımı',
    'privacy.section3.content': 'Bu politikada açıklanan durumlar dışında, açık rızanız olmadan kişisel bilgilerinizi üçüncü taraflara satmayız, takas etmeyiz veya başka bir şekilde aktarmayız. Web sitemizin işletilmesinde ve hizmetlerimizin sağlanmasında bize yardımcı olan hizmet sağlayıcılarla veya yasalar gerektirdiğinde bilgilerinizi paylaşabiliriz.',
    'privacy.section4.title': 'Veri Güvenliği',
    'privacy.section4.content': 'Kişisel bilgilerinizi yetkisiz erişime, değiştirilmeye, ifşa edilmeye veya imha edilmeye karşı korumak için uygun güvenlik önlemlerini uygularız. Ancak, internet üzerinden hiçbir iletim yöntemi veya elektronik depolama yöntemi %100 güvenli değildir.',
    'privacy.section5.title': 'Çerezler ve Takip',
    'privacy.section5.content': 'Web sitemizdeki deneyiminizi geliştirmek, kullanım şekillerini analiz etmek ve içeriği kişiselleştirmek için çerezler ve benzer takip teknolojileri kullanırız. Tarayıcı tercihleriniz aracılığıyla çerez ayarlarını kontrol edebilirsiniz.',
    'privacy.section6.title': 'Haklarınız',
    'privacy.section6.content': 'Kişisel bilgilerinize erişme, bunları güncelleme veya silme hakkına sahipsiniz. Ayrıca bizden gelen belirli iletişimleri almaktan vazgeçebilirsiniz. Bu hakları kullanmak için lütfen aşağıda verilen bilgileri kullanarak bizimle iletişime geçin.',
    'privacy.section7.title': 'Bu Politikadaki Değişiklikler',
    'privacy.section7.content': 'Bu gizlilik politikasını zaman zaman güncelleyebiliriz. Herhangi bir değişiklik olduğunda, yeni politikayı bu sayfada yayınlayarak ve "son güncelleme" tarihini güncelleyerek sizi bilgilendireceğiz.',
    'privacy.contact.title': 'Bize Ulaşın',
    'privacy.contact.content': 'Bu Gizlilik Politikası hakkında sorularınız varsa, lütfen bizimle iletişime geçin:',
    'privacy.contact.email': 'zyrachains@gmail.com',
    'report.heading': 'Dolandırıcılık veya Sahtekarlık Faaliyeti Bildir',
    'report.title': 'Dolandırıcılık Bildir - Zyrachain Pi Network Ekosistem Merkezi',
    'report.description': 'Pi Network topluluğunu korumaya yardımcı olmak için şüpheli veya sahtekarlık faaliyetlerini bildirin.',
    'report.intro': 'Dolandırıcılık veya sahtekarlık gibi görünen şüpheli bir cüzdan adresi, proje veya faaliyetle karşılaştıysanız, lütfen aşağıdaki formu kullanarak bildirin. Ekibimiz gönderinizi inceleyecek ve topluluğu korumak için uygun önlemi alacaktır.',
    'report.success_message': 'Bildiriminiz için teşekkür ederiz! Güvenlik ekibimiz bilgileri inceleyecek ve uygun önlemi alacaktır. Pi Network ekosistemini güvende tutmamıza yardımcı olduğunuz için teşekkür ederiz.',
    'report.form.wallet_address': 'Cüzdan Adresi (varsa)',
    'report.form.wallet_address_placeholder': 'Şüpheli cüzdan adresini girin',
    'report.form.description': 'Dolandırıcılık/Sahtekarlık Açıklaması',
    'report.form.description_placeholder': 'Lütfen ne olduğunu ve bunun neden bir dolandırıcılık veya sahtekarlık faaliyeti olduğuna inandığınızı detaylı bir şekilde açıklayın...',
    'report.form.evidence': 'Kanıt (Opsiyonel)',
    'report.form.evidence_placeholder': 'Bildiriminizi destekleyen ek kanıtlar, ekran görüntüleri veya bağlantılar...',
    'report.form.contact': 'İletişim Bilgileriniz (Opsiyonel)',
    'report.form.contact_placeholder': 'Takip soruları için size ulaşabileceğimiz e-posta adresi',
    'report.form.submit': 'Bildirimi Gönder',
    'report.info.title': 'Neleri Bildirmelisiniz',
    'report.info.description': 'Lütfen aşağıdakilerden herhangi birini bildirin:',
    'report.info.items': [
        'Sahte Pi Network projeleri veya uygulamaları',
        'Kimlik avı girişimleri veya sahte web siteleri',
        'Dolandırıcılıkla ilişkili şüpheli cüzdan adresleri',
        'Sahte çekilişler veya airdrop\'lar',
        'Resmi Pi Network hesaplarının taklit edilmesi',
        'Diğer sahtekarlık faaliyetleri'
    ],
    'report.info.note': 'Not: Tüm bildirimleri ciddiye alıyor ve her vakayı kapsamlı bir şekilde araştıracağız. Gizliliğiniz süreç boyunca korunacaktır.',
    'assets.search_placeholder': 'Kod veya ihraççıya göre ara...',
    'assets.testnet_warning': 'Pi Network Mainnet verileri. Mainnet'te henüz özel varlık bulunmamaktadır.',
    'monitor.balance_trend': 'Bakiye Eğilimi',
    'monitor.scanned': 'tarandı',
    'home.monitors.wallets_tracked': 'İzlenen Cüzdanlar',
    'home.monitors.current_balance': 'Güncel Bakiye',
    'home.monitors.net_24h': 'Net 24s',
    'home.monitors.total_out': 'Toplam Çıkış',
    'home.monitors.confirmed_changes': 'Onaylı Değişiklikler',
    'home.monitors.starting_balance': 'Başlangıç Bakiyesi',
    'home.monitors.aggregate_balance_trend': 'Toplam Bakiye Eğilimi',
    'home.monitors.recent_balance_changes': 'Son Bakiye Değişiklikleri',
    'home.monitors.no_changes_recorded': 'Yakın zamanda kayıtlı değişiklik yok.',
    'home.monitors.per_exchange_flow': 'Borsa Bazında 24s Akış',
    'home.monitors.inflow': 'Giriş',
    'home.monitors.outflow': 'Çıkış',
    'home.monitors.open_full_tracker': '{{type}} takipçisini tam aç',
    'home.monitors.core_team_wallets': 'Çekirdek Takım Cüzdanları',
    'home.monitors.exchange_wallets': 'Borsa (CEX) Cüzdanları',
    'home.monitors.data_unavailable': '{{title}} verileri geçici olarak kullanılamıyor. İzleme hizmetinin çalıştığından emin olun.',
}
