export const language_zh={
    "nav.home": "首页",
    "nav.cexs": "CEXs 和核心团队",
    "nav.operations": "操作",
    "nav.transactions": "交易",
    "nav.blocks": "区块",
    "nav.nodes": "节点",
    "nav.stats": "统计",
    "stats.accounts": "账户分布",
    "stats.unlocks": "Pi 解锁 (30 天)",
    "stats.unlocks_monthly": "Pi 解锁 (月度)",
    "stats.domain_auction": "域名拍卖统计",
    "stats.largest_tx": "最大交易",
    "stats.migrate": "主网迁移统计",
    "search.placeholder": "搜索...",
    "operations.self_transfer": "自我转账",
    "operations.domain_auction": "域名拍卖",
    "operations.claim_claimable_balance": "领取 π",
    "operations.create_account": "创建账户",
    "operations.payment": "支付",
    "operations.path_payment_strict_receive": "严格接收路径支付",
    "operations.path_payment_strict_send": "严格发送路径支付",
    "operations.manage_sell_offer": "管理卖出报价",
    "operations.create_passive_sell_offer": "创建被动卖出报价",
    "operations.set_options": "设置选项",
    "operations.change_trust": "更改信任",
    "operations.allow_trust": "允许信任",
    "operations.account_merge": "账户合并",
    "operations.inflation": "通货膨胀",
    "operations.manage_data": "管理数据",
    "operations.bump_sequence": "提升序列",
    "operations.manage_buy_offer": "管理买入报价",
    "operations.create_passive_buy_offer": "创建被动买入报价",
    "operations.create_claimable_balance": "创建可领取余额",
    "operations.claim_claimable_balance_atom": "领取余额",
    "operations.deposit": "存入",
    "operations.withdraw": "提取",
    "operations.pay": "支付",
    "operations.to": "至",
    "operations.from": "从",
    "operations.claimant": "领取人",
    "operations.with_starting_balance": "起始余额为",
    "operations.claim": "领取",
    "operations.heading": "探索 Pi 网络区块链上的最新操作",
    "operations.title": "Pi 网络上的最新操作",
    "operations.description": "探索 Pi 网络区块链上的最新操作。",
    "operations.source_account": "源账户",
    "operations.operation": "操作",
    "operations.amount": "数量",
    "operations.tx": "交易",
    "operations.time": "时间",
    "pagination.previous": "上一页",
    "pagination.next": "下一页",
    "pagination.page": "页码",
    "account.title": "账户 {{address}} - Pi 网络浏览器",
    "account.heading": "账户详情",
    "account.heading_with_address": "账户 {{address}}",
    "account.description": "Pi 网络上账户 {{address}} 的详细信息。",
    "account.loading": "加载账户详情中...",
    "account.not_found": "找不到账户。",
    "account.scam_warning_title": "诈骗警告",
    "account.scam_warning_description": "根据社区报告，此钱包地址已被标记为不安全。它可能与诈骗、私钥泄露或未授权访问有关。在进行任何交易前请谨慎行事。",
    "account.overview": "概览",
    "account.available_balance": "可用余额",
    "account.last_modified_time": "最后修改时间",
    "account.locking": "锁定中",
    "account.total_locking": "总锁定 ({{count}} 项)",
    "account.next_unlock_time": "下次解锁时间",
    "account.claimable": "可领取",
    "account.amount": "金额",
    "account.number_of_items": "项目数量",
    "account.over_100_items": "超过100项",
    "account.tx_hash": "交易哈希",
    "account.operation_count": "操作数量",
    "account.fee": "费用",
    "account.created_at": "创建时间",
    "account.account": "账户",
    "account.effect": "效果",
    "account.sponsor": "赞助商",
    "account.predicate": "条件",
    "account.create_time": "创建时间",
    "account.latest_100_claimable": "最新100个可领取余额",
    "account.tabs.operations": "操作",
    "account.tabs.transactions": "交易",
    "account.tabs.effects": "效果",
    "account.tabs.claimable_balances": "可领取余额",
    "effects.account_credited": "账户已入账",
    "effects.account_debited": "账户已扣款",
    "effects.account_created": "账户已创建",
    "effects.claimable_balance_created": "可领取余额已创建",
    "effects.claimable_balance_claimed": "可领取余额已领取",
    "effects.claimable_balance_claimant_created": "可领取余额领取人已创建",
    "effects.account_removed": "账户已删除",
    "effects.account_thresholds_updated": "账户阈值已更新",
    "effects.account_home_domain_updated": "账户主域名已更新",
    "effects.account_flags_updated": "账户标志已更新",
    "effects.account_inflation_destination_updated": "账户通胀目标已更新",
    "effects.signer_created": "签署人已创建",
    "effects.signer_removed": "签署人已删除",
    "effects.signer_updated": "签署人已更新",
    "effects.trustline_removed": "信任线已删除",
    "effects.trustline_updated": "信任线已更新",
    "effects.trustline_authorized": "信任线已授权",
    "effects.trustline_deauthorized": "信任线已取消授权",
    "effects.offer_created": "报价已创建",
    "effects.offer_removed": "报价已删除",
    "effects.offer_updated": "报价已更新",
    "effects.trade": "交易已执行",
    "effects.data_created": "数据已创建",
    "effects.data_removed": "数据已删除",
    "effects.data_updated": "数据已更新",
    "effects.sequence_bumped": "序列已提升",
    "effects.liquidity_pool_created": "流动性池已创建",
    "effects.liquidity_pool_removed": "流动性池已删除",
    "effects.liquidity_pool_deposited": "流动性池已存入",
    "effects.liquidity_pool_withdrew": "流动性池已提取",
    "effects.liquidity_pool_trade": "流动性池交易",
    "effects.liquidity_pool_revoked": "流动性池已撤销",
    "effects.contract_credited": "合约已入账",
    "effects.contract_debited": "合约已扣款",
    "effects.claimable_balance_sponsorship_removed": "可领取余额赞助已移除",
    "account_stats.heading": "Pi 账户统计 - 余额分布和顶级账户",
    "account_stats.title": "Pi 账户统计 - 余额分布和顶级账户",
    "account_stats.description": "查看 Pi 网络上最富有的 Pi 账户和整体余额分布。",
    "account_stats.intro_text": "探索所有账户中 Pi 的分布并查看顶级 Pi 持有者。",
    "account_stats.distribution_chart_title": "Pi 持有者分布",
    "account_stats.categories_title": "分布类别",
    "account_stats.top_accounts_title": "顶级 Pi 账户",
    "account_stats.accounts": "账户",
    "account_stats.of_total": "占总数",
    "account_stats.table.category": "类别",
    "account_stats.table.balance_range": "余额范围",
    "account_stats.table.usd_value": "美元价值",
    "account_stats.table.accounts": "账户数",
    "account_stats.table.percentage": "总数百分比",
    "account_stats.table.total": "总计",
    "account_stats.table.rank": "排名",
    "account_stats.table.account": "账户",
    "account_stats.table.balance": "余额",
    "account_stats.table.value": "价值",
    "account_stats.table.supply_percentage": "总供应量百分比",
    "account_stats.categories.whales": "鲸鱼",
    "account_stats.categories.sharks": "鲨鱼",
    "account_stats.categories.dolphins": "海豚",
    "account_stats.categories.tunas": "金枪鱼",
    "account_stats.categories.fish": "鱼",
    "account_stats.categories.shrimps": "虾",
    "account_stats.categories.plankton": "浮游生物",
    "account_stats.categories.microbes": "微生物",
    "number.billion_short": "亿",
    "number.million_short": "百万",
    "number.thousand_short": "千",
    "common.loading": "加载中...",
    "common.sponsored": "赞助",
    "common.ad": "广告",
    "common.ad_not_available": "您所在地区无法提供赞助内容",
    "blocks.heading": "探索 Pi 网络区块链上的最新区块",
    "blocks.title": "Pi 网络上的最新区块",
    "blocks.description": "探索 Pi 网络区块链上的最新区块。",
    "blocks.sequence": "序列",
    "blocks.hash": "哈希",
    "blocks.transactions": "交易",
    "blocks.operations": "操作",
    "blocks.time": "时间",
    "blocks.successful": "成功",
    "blocks.failed": "失败",
    "block.title": "区块 #{{sequence}} - Pi 网络浏览器",
    "block.heading": "区块 #{{sequence}}",
    "block.description": "Pi 网络区块链上区块 #{{sequence}} 的详细信息。",
    "block.loading": "加载区块详情中...",
    "block.not_found": "找不到区块。",
    "block.information": "区块信息",
    "block.hash": "哈希",
    "block.previous_hash": "前序哈希",
    "block.sequence": "序列",
    "block.time": "时间",
    "block.total_coins": "总币量",
    "block.fee_pool": "手续费池",
    "block.base_fee": "基础手续费",
    "block.base_reserve": "基础准备金",
    "block.protocol_version": "协议版本",
    "block.tx_hash": "交易哈希",
    "block.operation_count": "操作数量",
    "block.fee": "手续费",
    "block.created_at": "创建时间",
    "block.tabs.transactions": "交易",
    "block.tabs.operations": "操作",
    "block.tabs.effects": "效果",
    "cex.heading": "CEX 和核心团队账户统计",
    "cex.title": "Pi 网络上的 CEX 和核心团队账户",
    "cex.description": "探索 Pi 网络区块链上的 CEX 和核心团队账户。",
    "cex.wallet_balances": "CEX 钱包余额",
    "cex.core_team_wallets": "Pi 核心团队钱包",
    "cex.cmc_ranking": "CMC 排名",
    "cex.exchange": "交易所",
    "cex.chart_link": "图表链接",
    "cex.signup_link": "注册链接",
    "cex.wallet_address": "钱包地址",
    "cex.balance_pi": "余额 (Pi)",
    "cex.balance_usd": "余额 (USD)",
    "cex.chart": "图表",
    "cex.signup": "注册",
    "cex.total": "总计",
    "cex.note": "备注",
    "cex.pi_foundation": "Pi 基金会",
    "cex.total_in": "总流入（近24小时）",
    "cex.total_out": "总流出（近24小时）",
    "cex.net_difference": "净流量（近24小时）",
    "cex.flow_data_updated": "流量数据最后更新（每30分钟刷新）",
    "cex.actions": "操作",
    "cex.filter_transactions_tooltip": "筛选此地址的交易",
    "cex.filter_txs_button": "筛选交易",
    "pct.nav": "核心团队",
    "cex_monitor.nav": "交易所",
    "pct.title": "核心团队钱包追踪器",
    "pct.subtitle": "我们频繁检查余额，仅显示已验证的变动。",
    "pct.tab_wallets": "钱包",
    "pct.tab_updates": "更新",
    "pct.tab_history": "历史",
    "pct.stat_tracked": "已追踪钱包",
    "pct.stat_starting": "起始余额",
    "pct.stat_current": "当前余额",
    "pct.stat_changes": "确认变动次数",
    "pct.stat_total_out": "总流出",
    "pct.stat_24h": "24小时净变动",
    "pct.section_wallets": "核心团队钱包列表",
    "pct.section_updates": "最近变动（7天）",
    "pct.section_history": "最新确认变动",
    "pct.latest_check": "最近检查：",
    "pct.scan_running": "扫描进行中",
    "pct.prev": "上一页",
    "pct.next": "下一页",
    "pct.wallets_index": "个钱包",
    "pct.footer_note": "浏览器链接将打开 Pi 官方区块浏览器。",
    "pct.col_wallet": "钱包",
    "pct.col_old": "旧余额",
    "pct.col_new": "新余额",
    "pct.col_change": "变动",
    "pct.col_detected": "检测时间",
    "pct.col_ledger": "账本",
    "pct.no_changes": "暂无确认变动。请稍后再查看。",
    "pct.loading": "加载中…",
    "pct.load_more": "加载更多",
    "pct.summary_error": "无法从服务器加载汇总数据。",
    "cex_monitor.title": "交易所钱包追踪器",
    "cex_monitor.subtitle": "已验证余额变动的交易所钱包。",
    "cex_monitor.tab_wallets": "钱包",
    "cex_monitor.tab_updates": "更新",
    "cex_monitor.tab_history": "历史",
    "cex_monitor.stat_tracked": "已追踪钱包",
    "cex_monitor.stat_starting": "起始余额",
    "cex_monitor.stat_current": "当前余额",
    "cex_monitor.stat_changes": "确认变动次数",
    "cex_monitor.stat_total_out": "总流出",
    "cex_monitor.stat_24h": "24小时净变动",
    "cex_monitor.section_wallets": "交易所钱包列表",
    "cex_monitor.section_updates": "最近变动（7天）",
    "cex_monitor.section_history": "最新确认变动",
    "cex_monitor.latest_check": "最近检查：",
    "cex_monitor.scan_running": "扫描进行中",
    "cex_monitor.prev": "上一页",
    "cex_monitor.next": "下一页",
    "cex_monitor.wallets_index": "个钱包",
    "cex_monitor.footer_note": "浏览器链接将打开 Pi 官方区块浏览器。",
    "cex_monitor.col_wallet": "钱包",
    "cex_monitor.col_old": "旧余额",
    "cex_monitor.col_new": "新余额",
    "cex_monitor.col_change": "变动",
    "cex_monitor.col_detected": "检测时间",
    "cex_monitor.col_ledger": "账本",
    "cex_monitor.no_changes": "暂无确认变动。请稍后再查看。",
    "cex_monitor.loading": "加载中…",
    "cex_monitor.load_more": "加载更多",
    "cex_monitor.summary_error": "无法从服务器加载 CEX 汇总数据。",
    "contact.heading": "联系我们",
    "contact.title": "联系 PiScan",
    "contact.description": "如有任何疑问或反馈，请联系 PiScan。",
    "contact.intro_text": "如果您有任何问题，请随时通过以下方式联系我们",
    "contact.email": "zyrachains@gmail.com",
    "contact.success_message": "感谢您与我们联系！我们将尽快回复您。",
    "contact.form.name": "您的姓名",
    "contact.form.email": "您的电子邮箱",
    "contact.form.message": "消息",
    "contact.form.submit": "发送消息",
    "home.heading": "探索 Pi 网络交易、钱包和统计数据",
    "home.title": "探索 Pi 网络交易、钱包和统计数据",
    "home.description": "探索 Pi 网络交易、钱包和统计数据",
    "home.market_cap": "市值",
    "home.price": "价格",
    "home.24h_change": "24小时变化",
    "home.pi_supply": "Pi 供应量",
    "home.circulating": "流通量",
    "home.locked": "锁定量",
    "home.cex_balance_total": "CEX 余额 (总计)",
    "home.view_all": "查看全部",
    "home.network_stats": "网络统计",
    "home.blocks": "区块",
    "home.tps": "TPS",
    "home.latest_transactions": "最新交易",
    "home.signature": "签名",
    "home.time": "时间",
    "home.block": "区块",
    "home.ops": "操作",
    "home.latest_operations": "最新操作",
    "home.source_account": "源账户",
    "home.operation": "操作",
    "home.amount": "数量",
    "home.tx": "交易",
    "nodes.heading": "Pi 网络节点地图和网络统计",
    "nodes.title": "Pi 网络节点和验证者",
    "nodes.description": "探索 Pi 网络节点、验证者和网络拓扑。查看节点的全球分布和连接性。",
    "nodes.active_nodes": "活跃节点",
    "nodes.validators": "验证者",
    "nodes.known_peers": "已知对等点",
    "nodes.disconnected_nodes": "断开连接节点",
    "nodes.network_graph": "网络图",
    "nodes.node_types": "节点类型",
    "nodes.validator": "验证者",
    "nodes.watcher": "观察者",
    "nodes.disconnected_private": "断开连接/私有",
    "nodes.click_to_highlight": "点击节点以突出显示其连接",
    "nodes.global_distribution": "全球分布",
    "nodes.mapped_nodes": "已映射节点",
    "nodes.node_details": "节点详情",
    "nodes.nodes": "节点",
    "nodes.address": "地址",
    "nodes.type": "类型",
    "nodes.location": "位置",
    "nodes.isp": "互联网服务提供商",
    "nodes.version": "版本",
    "nodes.trust": "信任",
    "nodes.trusted_by": "被信任",
    "nodes.status": "状态",
    "nodes.status.connected": "已连接",
    "nodes.status.disconnected": "已断开",
    "nodes.status.private": "私有",
    "nodes.active_quorum_sets": "活跃法定人数集",
    "nodes.active": "活跃",
    "nodes.quorum_hash": "法定人数哈希",
    "nodes.node_id": "节点 ID",
    "nodes.unknown": "未知",
    "nodes.core_team": "核心团队",
    "nodes.tooltip.node_id": "节点 ID",
    "nodes.tooltip.address": "地址",
    "nodes.tooltip.type": "类型",
    "nodes.tooltip.status": "状态",
    "nodes.tooltip.version": "版本",
    "nodes.tooltip.location": "位置",
    "nodes.tooltip.not_accessible": "无法访问",
    "nodes.phantom_validators": "幻影验证者",
    "nodes.country_statistics": "国家统计",
    "nodes.city_statistics": "城市统计",
    "nodes.online_nodes_only": "仅在线节点",
    "nodes.country": "国家",
    "nodes.city": "城市",
    "nodes.connected_nodes": "已连接节点",
    "nodes.no_country_data": "暂无国家数据",
    "nodes.no_city_data": "暂无城市数据",
    "nodes_testnet.heading": "Pi网络测试网节点统计",
    "nodes_testnet.title": "Pi网络测试网节点",
    "nodes_testnet.description": "探索Pi网络测试网节点统计和全球分布。",
    "nodes_testnet.summary_title": "测试网节点概览",
    "nodes_testnet.summary_description": "Pi网络测试网节点及其活动水平的实时统计。",
    "nodes_testnet.total_peers": "总节点数",
    "nodes_testnet.active_peers": "活跃节点数",
    "nodes_testnet.activity_rate": "活跃率",
    "nodes_testnet.country_statistics": "国家统计",
    "nodes_testnet.city_statistics": "城市统计",
    "nodes_testnet.country": "国家",
    "nodes_testnet.city": "城市",
    "nodes_testnet.total_nodes": "总节点数",
    "nodes_testnet.active_nodes": "活跃节点数",
    "nodes_testnet.active_rate": "活跃率",
    "report_scam.heading": "举报诈骗钱包",
    "report_scam.title": "在 PiScan 上举报诈骗钱包",
    "report_scam.description": "举报涉及欺诈或诈骗活动的钱包地址。",
    "report_scam.intro_text": "如果您遇到了涉及欺诈或诈骗活动的可疑钱包地址，请使用以下表格进行举报。我们的团队将审核您的提交，如果确认为诈骗，我们将在 PiScan 上将该钱包标记为诈骗，以警示社区。",
    "report_scam.success_message": "感谢您的举报！我们的团队将尽快审核。",
    "report_scam.form.wallet_address": "钱包地址",
    "report_scam.form.wallet_placeholder": "输入诈骗钱包地址",
    "report_scam.form.reason": "举报原因",
    "report_scam.form.reason_placeholder": "描述为什么怀疑此钱包涉及诈骗活动",
    "report_scam.form.email": "您的电子邮箱（可选）",
    "report_scam.form.email_placeholder": "输入您的电子邮箱（可选）",
    "report_scam.form.email_note": "我们可能会联系您了解更多详情。",
    "report_scam.form.submit": "提交举报",
    "transaction.title": "Pi 网络上的交易 #{{id}}",
    "transaction.heading": "交易详情",
    "transaction.description": "Pi 网络区块链上交易 #{{id}} 的详细信息。",
    "transaction.loading": "正在加载交易详情...",
    "transaction.not_found": "未找到交易。",
    "transaction.hash": "哈希值",
    "transaction.ledger_block": "账本（区块）",
    "transaction.result": "结果",
    "transaction.source_account": "源账户",
    "transaction.fee_account": "手续费账户",
    "transaction.fee": "手续费",
    "transaction.operation_count": "操作数量",
    "transaction.summary": "摘要",
    "transaction.operations": "操作",
    "transaction.effects": "效果",
    "transaction.account": "账户",
    "transaction.operation": "操作",
    "transaction.effect": "效果",
    "transaction.amount": "金额",
    "transaction.successful": "成功",
    "transaction.failed": "失败",
    "transaction.loading_details": "正在加载交易详情...",
    "transaction.with_operations": "包含 {{count}} 个操作的交易",
    "transaction.core_team_distributed": "Pi 核心团队分发了",
    "transaction.to": "给",
    "transaction.accounts": "账户",
    "transaction.locked_for_days": "，锁定 {{days}} 天",
    "transaction.locked_range_days": "，锁定期从 {{minDays}} 天到 {{maxDays}} 天不等",
    "transaction.created_at": "创建时间",
    "unlock_stats.heading": "Pi 解锁统计 - 未来 30 天",
    "unlock_stats.title": "Pi 解锁统计 - 未来 30 天",
    "unlock_stats.description": "查看未来 30 天的 Pi 加密货币解锁统计预测。",
    "unlock_stats.intro_text": "未来 30 天的 Pi 解锁基于可领取余额，可能是用户锁定的或由 Pi 核心团队分配的。尚未包含在可领取余额中的未发布 Pi 无法追踪。请定期查看更新。所有时间均为 UTC。",
    "unlock_stats.today_note": "今天的解锁金额代表从现在到当天结束（UTC）将要解锁的剩余 Pi。",
    "unlock_stats.updated_at": "数据更新于：",
    "unlock_stats.unknown": "未知",
    "unlock_stats.total_locked": "总锁定 Pi",
    "unlock_stats.total_next_30": "未来 30 天总解锁量",
    "unlock_stats.of_total_locked": "占总锁定量",
    "unlock_stats.avg_daily": "平均每日解锁量",
    "unlock_stats.per_day": "每天",
    "unlock_stats.highest_day": "最高解锁日",
    "unlock_stats.on": "在",
    "unlock_stats.chart_title": "Pi 解锁图表 - 未来 30 天",
    "unlock_stats.data_table": "解锁数据表",
    "unlock_stats.date": "日期",
    "unlock_stats.amount": "金额",
    "unlock_stats.value": "价值",
    "unlock_stats.pi_unlock": "Pi 解锁",
    "unlock_stats.y_axis_label": "Pi 解锁（百万计）",
    "unlock_stats.monthly_heading": "每月Pi解锁统计",
    "unlock_stats.monthly_title": "每月Pi解锁统计",
    "unlock_stats.total_next_12": "未来 12 个月总解锁量",
    "unlock_stats.monthly_description": "查看每月Pi加密货币解锁统计",
    "unlock_stats.monthly_intro_text": "查看按月统计的Pi加密货币解锁情况。",
    "unlock_stats.monthly_note": "统计基于符合条件的解锁请求。",
    "unlock_stats.monthly_chart_title": "每月Pi解锁统计图表",
    "unlock_stats.total_forecast": "总统计",
    "unlock_stats.monthly_data_table": "每月解锁数据",
    "unlock_stats.total_locking": "总锁定量",
    "unlock_stats.avg_monthly": "每月平均",
    "unlock_stats.highest_month": "最高月份",
    "unlock_stats.per_month": "每月",
    "unlock_stats.in": "于",
    "unlock_stats.month": "月份",
    "unlock_stats.view_daily": "查看每日解锁统计",
    "unlock_stats.view_monthly": "查看每月解锁统计",
    "common.loading_error": "加载数据时出错。请稍后再试。",
    "settings.aria_label": "打开设置",
    "settings.language": "语言",
    "settings.appearance": "外观",
    "settings.dark_mode": "深色模式",
    "settings.light": "浅色",
    "settings.dark": "深色",
    "transactios.heading": "探索 Pi 网络区块链上的最新交易",
    "transactions.title": "Pi 网络上的最新交易",
    "transactions.description": "探索 Pi 网络区块链上的最新交易。",
    "domain_auction_stats.heading": "Pi 域名拍卖统计",
    "domain_auction_stats.title": "Pi 域名拍卖统计 | Pi 网络统计",
    "domain_auction_stats.description": "分析 Pi 网络域名拍卖，显示不同价格区间的出价分布以及目前已出价的 Pi 总额。",
    "domain_auction_stats.intro_text": "本页面提供 Pi 域名拍卖分析，重点展示不同价格区间的出价分布。",
    "domain_auction_stats.last_updated": "最后更新",
    "domain_auction_stats.summary_title": "拍卖出价概览",
    "domain_auction_stats.total_bids": "总出价次数",
    "domain_auction_stats.total_pi_bid": "已出价 Pi 总额",
    "domain_auction_stats.estimated_value": "预估价值 (USD)",
    "domain_auction_stats.pi_price": "当前 Pi 价格",
    "domain_auction_stats.distribution_title": "出价分布",
    "domain_auction_stats.chart_title": "出价价格分布",
    "domain_auction_stats.details_title": "实时出价明细",
    "domain_auction_stats.bids": "出价",
    "domain_auction_stats.of_total": "占总出价",
    "domain_auction_stats.bid_count": "出价次数",
    "domain_auction_stats.ranges.low": "低额出价",
    "domain_auction_stats.ranges.medium": "标准出价",
    "domain_auction_stats.ranges.high": "高级出价",
    "domain_auction_stats.ranges.premium": "尊享出价",
    "domain_auction_stats.ranges.elite": "顶级出价",
    "domain_auction_stats.table.price_range": "出价区间",
    "domain_auction_stats.table.bid_count": "出价次数",
    "domain_auction_stats.table.percentage": "占比",
    "domain_auction_stats.table.total": "总出价",
    "domain_auction_stats.highest_bid": "最高出价",
    "domain_auction_stats.top_bids_title": "最高出价列表",
    "domain_auction_stats.table.account": "账户",
    "domain_auction_stats.table.bid_amount": "出价金额",
    "domain_auction_stats.table.usd_value": "美元价值",
    "largest_tx.heading": "最大 Pi 交易（过去 24 小时）",
    "largest_tx.title": "过去 24 小时内最大 Pi 交易 - PiScan",
    "largest_tx.description": "探索过去 24 小时 Pi Network 区块链上的最大 Pi 交易。",
    "largest_tx.list_heading": "按交易金额排名（过去 24 小时）",
    "largest_tx.rank": "排名",
    "largest_tx.transaction": "交易",
    "largest_tx.account": "账户",
    "largest_tx.amount": "金额 (π)",
    "largest_tx.date": "日期 & 时间",
    "largest_tx.no_data": "过去 24 小时内无交易数据。",
    "largest_tx.fetch_error": "无法获取交易数据。",
    "largest_tx.loading": "正在加载最大交易...",
    "largest_tx.largest_amount": "最大交易金额（过去 24 小时）",
    "largest_tx.latest_large_tx": "最新大额交易（过去 24 小时）",
    "largest_tx.total_value": "总价值（前 100 笔交易，过去 24 小时）",
    "migrate_stats.heading": "Pi 迁移统计",
    "migrate_stats.title": "Pi 迁移至主网统计 - PiScan",
    "migrate_stats.description": "跟踪最近几天 Pi 迁移至主网的统计数据。",
    "migrate_stats.last_updated": "最后更新",
    "migrate_stats.daily_migration": "每日迁移量",
    "migrate_stats.daily_stats": "每日迁移统计",
    "migrate_stats.loading": "正在加载迁移统计...",
    "migrate_stats.no_data": "暂无迁移数据。",
    "migrate_stats.fetch_error": "无法获取迁移数据。",
    "migrate_stats.date": "日期",
    "migrate_stats.amount": "金额 (π)",
    "migrate_stats.percentage": "百分比 (%)",
    "migrate_stats.total": "总计",
    "migrate_stats.pi_migrated": "已迁移总 Pi",
    "migrate_stats.date_label": "日期：{{date}}",
    "migrate_stats.usd_value": "美元价值",
    "migrate_stats.at_price": "当前价格",
    "migrate_stats.current_price_note": "美元价值按当前 Pi 价格 {{price}} 每 π 计算。",
    "transactions_filter.heading": "筛选交易",
    "transactions_filter.title": "筛选交易 | Pi Scan",
    "transactions_filter.description": "根据地址、金额和其他条件筛选并搜索 Pi Network 交易。",
    "transactions_filter.address_required_error": "请输入地址。",
    "transactions_filter.min_amount_required_error": "请输入最小金额。",
    "transactions_filter.amount_too_low_error": "金额不能少于 10,000。",
    "transactions_filter.min_exceeds_max_error": "最小金额不能超过最大金额。",
    "transactions_filter.filter_options": "筛选选项",
    "transactions_filter.address": "地址",
    "transactions_filter.address_placeholder": "输入账户地址",
    "transactions_filter.min_amount": "最小金额 (Pi)",
    "transactions_filter.min_amount_placeholder": "例如：10000",
    "transactions_filter.max_amount": "最大金额 (Pi)",
    "transactions_filter.max_amount_placeholder": "例如：100000",
    "transactions_filter.apply_filters": "应用",
    "transactions_filter.clear": "清除",
    "transactions_filter.no_results": "未找到符合条件的交易。",
    "transactions_filter.results": "结果",
    "transactions_filter.table.hash": "交易哈希",
    "transactions_filter.table.time": "时间",
    "transactions_filter.table.from": "发送方",
    "transactions_filter.table.to": "接收方",
    "transactions_filter.table.amount": "金额 (Pi)",
    "transactions_filter.apply_filters_prompt": "请先应用筛选以查看结果。",
    "transactions_filter.table.tx": "交易",
    "transactions_filter.table.detail_button": "查看详情",
    "transactions_filter.operation_text.payment": "从 {{from}} 向 {{to}} 支付 {{amount}} Pi",
    "transactions_filter.operation_text.unknown": "未知操作",
    "report.heading": "举报诈骗或欺诈活动",
    "report.title": "举报诈骗 - Zyrachain Pi Network 生态系统中心",
    "report.description": "举报可疑或欺诈活动，帮助保护 Pi Network 社区。",
    "report.intro": "如果您遇到了可疑的钱包地址、项目或看起来像是欺诈或诈骗的活动，请使用以下表格进行举报。我们的团队将审核您的提交并采取适当措施保护社区。",
    "report.success_message": "感谢您的举报！我们的安全团队将审核信息并采取适当措施。感谢您帮助维护 Pi Network 生态系统的安全。",
    "report.form.wallet_address": "钱包地址（如适用）",
    "report.form.wallet_address_placeholder": "输入可疑的钱包地址",
    "report.form.description": "诈骗/欺诈描述",
    "report.form.description_placeholder": "请提供详细描述，说明发生了什么以及为什么您认为这是诈骗或欺诈活动...",
    "report.form.evidence": "证据（可选）",
    "report.form.evidence_placeholder": "任何支持您举报的额外证据、截图或链接...",
    "report.form.contact": "您的联系方式（可选）",
    "report.form.contact_placeholder": "用于后续联系的电子邮箱地址",
    "report.form.submit": "提交举报",
    "report.info.title": "举报范围",
    "report.info.description": "请举报以下任何情况：",
    "report.info.items": ["虚假的 Pi Network 项目或应用", "钓鱼攻击或虚假网站", "参与诈骗的可疑钱包地址", "虚假的赠送或空投活动", "冒充 Pi Network 官方账号", "任何其他欺诈活动"],
    "report.info.note": "注意：我们认真对待所有举报，并将对每个案例进行彻底调查。在整个过程中，您的隐私将受到保护。",
    "docs.heading": "开发者文档",
    "docs.title": "文档和 API - Zyrachain",
    "docs.description": "用于将 Pi Network 数据集成到您的应用程序中的开发者文档和 API 端点。",
    "docs.hero_subtitle": "使用 Pi Network 数据构建出色的应用程序。通过我们全面的 API 访问实时区块链信息、DApp 列表和社区功能。",
    "docs.features.real_time": "实时数据",
    "docs.features.restful": "RESTful API",
    "docs.features.secure": "安全可靠",
    "docs.tabs.overview": "概览",
    "docs.tabs.endpoints": "API 端点",
    "docs.tabs.integration": "Pi 集成",
    "docs.tabs.examples": "示例",
    "docs.tabs.support": "支持",
    "docs.blockchain_data.title": "区块链数据 API",
    "docs.blockchain_data.description": "访问实时 Pi Network 区块链信息",
    "docs.blockchain_data.features": ["交易详情和历史记录", "区块信息和统计", "账户余额和操作", "网络指标（TPS、供应量等）"],
    "docs.dapp_directory.title": "DApp 目录 API",
    "docs.dapp_directory.description": "发现并管理 Pi Network 应用",
    "docs.dapp_directory.features": ["浏览精选 DApp", "按类别筛选", "提交新应用", "跟踪热门应用"],
    "docs.getting_started.title": "入门指南",
    "docs.getting_started.description": "按照以下步骤开始集成我们的 API",
    "docs.step1.title": "选择您的 API",
    "docs.step1.description": "从区块链数据、DApp 目录或社区 API 中选择",
    "docs.step2.title": "进行 API 调用",
    "docs.step2.description": "使用标准 HTTP 方法调用我们的 RESTful 端点",
    "docs.step3.title": "构建出色的应用",
    "docs.step3.description": "为您的用户创建强大的 Pi Network 应用",
    "docs.base_url.title": "基础 URL",
    "docs.base_url.description": "所有 API 请求应发往此基础 URL",
    "docs.base_url.value": "https://clubhouse-pi.io/api/v1",
    "docs.endpoints.stats.title": "区块链统计",
    "docs.endpoints.stats.description": "获取实时 Pi Network 统计",
    "docs.endpoints.stats.method": "GET",
    "docs.endpoints.stats.path": "/api/v1/stats",
    "docs.endpoints.stats.response": "返回网络统计，包括 TPS、供应量等",
    "docs.endpoints.transactions.title": "最新交易",
    "docs.endpoints.transactions.description": "获取网络上最新的交易",
    "docs.endpoints.transactions.method": "GET",
    "docs.endpoints.transactions.path": "/api/v1/transactions",
    "docs.endpoints.transactions.params": "limit, cursor, order",
    "docs.endpoints.blocks.title": "最新区块",
    "docs.endpoints.blocks.description": "获取网络上最新的区块",
    "docs.endpoints.blocks.method": "GET",
    "docs.endpoints.blocks.path": "/api/v1/blocks",
    "docs.endpoints.blocks.params": "limit, cursor, order",
    "docs.endpoints.account.title": "账户详情",
    "docs.endpoints.account.description": "获取详细的账户信息",
    "docs.endpoints.account.method": "GET",
    "docs.endpoints.account.path": "/api/v1/accounts/{address}",
    "docs.endpoints.account.params": "address（必填）",
    "docs.endpoints.transaction.title": "交易详情",
    "docs.endpoints.transaction.description": "获取详细的交易信息",
    "docs.endpoints.transaction.method": "GET",
    "docs.endpoints.transaction.path": "/api/v1/transactions/{hash}",
    "docs.endpoints.transaction.params": "hash（必填）",
    "docs.integration.title": "Pi Network 集成",
    "docs.integration.description": "了解如何集成 Pi Network 认证和支付",
    "docs.integration.auth.title": "认证",
    "docs.integration.auth.description": "在您的应用中使用 Pi Network 认证",
    "docs.integration.payments.title": "支付",
    "docs.integration.payments.description": "在您的应用中接受 Pi 支付",
    "docs.examples.title": "代码示例",
    "docs.examples.description": "常见用例的即用代码示例",
    "docs.examples.javascript.title": "JavaScript/Node.js",
    "docs.examples.python.title": "Python",
    "docs.examples.curl.title": "cURL",
    "docs.support.title": "支持和资源",
    "docs.support.description": "获取帮助并查找额外资源",
    "docs.support.community.title": "社区",
    "docs.support.community.description": "加入我们的开发者社区获取支持和讨论",
    "docs.support.documentation.title": "文档",
    "docs.support.documentation.description": "全面的指南和教程",
    "docs.support.api_reference.title": "API 参考",
    "docs.support.api_reference.description": "完整的 API 端点文档",
    "terms.heading": "服务条款",
    "terms.title": "服务条款 - Zyrachain",
    "terms.description": "管理 Zyrachain 服务和平台使用的条款和条件。",
    "terms.section1.title": "条款接受",
    "terms.section1.content": "访问和使用 Zyrachain（以下简称服务），即表示您接受并同意受本协议条款和规定的约束。如果您不同意遵守上述内容，请不要使用此服务。",
    "terms.section2.title": "使用许可",
    "terms.section2.content": "授予临时下载 Zyrachain 网站上的材料（信息或软件）一份副本的许可，仅供个人、非商业性临时查看。这是许可授予，而非所有权转让，根据此许可，您不得：修改或复制材料；将材料用于任何商业目的或公开展示；尝试对 Zyrachain 网站上包含的任何软件进行逆向工程；从材料中删除任何版权或其他专有标记；或将材料转让给他人或在任何其他服务器上镜像材料。",
    "terms.section3.title": "免责声明",
    "terms.section3.content": "Zyrachain 网站上的材料按原样提供。Zyrachain 不作任何明示或暗示的保证，并特此声明并否认所有其他保证，包括但不限于适销性、特定用途适用性或不侵犯知识产权或其他侵权行为的暗示保证或条件。",
    "terms.section4.title": "责任限制",
    "terms.section4.content": "在任何情况下，Zyrachain 或其供应商均不对因使用或无法使用 Zyrachain 网站上的材料而产生的任何损害（包括但不限于数据丢失或利润损失，或因业务中断造成的损害）承担责任，即使 Zyrachain 或 Zyrachain 授权代表已口头或书面被告知此类损害的可能性。",
    "terms.section5.title": "材料准确性",
    "terms.section5.content": "Zyrachain 网站上出现的材料可能包含技术、排版或摄影错误。Zyrachain 不保证其网站上的任何材料准确、完整或最新。Zyrachain 可随时更改其网站上包含的材料，恕不另行通知。",
    "terms.section6.title": "链接",
    "terms.section6.content": "Zyrachain 未审查所有链接到其网站的站点，也不对任何此类链接站点的内容负责。包含任何链接并不暗示 Zyrachain 对该站点的认可。使用任何此类链接网站的风险由用户自行承担。",
    "terms.section7.title": "修改",
    "terms.section7.content": "Zyrachain 可随时修改其网站的服务条款，恕不另行通知。使用本网站即表示您同意受当时最新版本的服务条款约束。",
    "terms.section8.title": "管辖法律",
    "terms.section8.content": "这些条款和条件受法律管辖并据其解释，您不可撤销地接受该地法院的专属管辖权。",
    "terms.contact.title": "联系信息",
    "terms.contact.content": "如果您对这些服务条款有任何疑问，请通过以下方式联系我们：",
    "terms.contact.email": "zyrachains@gmail.com",
    "privacy.heading": "隐私政策",
    "privacy.title": "隐私政策 - Zyrachain Pi Network 生态系统中心",
    "privacy.description": "我们如何收集、使用和保护您的个人信息。",
    "privacy.section1.title": "我们收集的信息",
    "privacy.section1.content": "我们收集您直接提供给我们的信息，例如当您创建账户、联系我们或使用我们的服务时。这可能包括您的姓名、电子邮箱地址、钱包地址以及您选择提供的任何其他信息。当您使用我们的服务时，我们还会自动收集某些信息，包括您的 IP 地址、浏览器类型、操作系统和使用模式。",
    "privacy.section2.title": "我们如何使用您的信息",
    "privacy.section2.content": "我们使用收集的信息来提供、维护和改进我们的服务，与您沟通，开发新功能，并保护我们的用户和公众。我们还可能使用您的信息向您发送技术通知、更新、安全警报和支持消息。",
    "privacy.section3.title": "信息共享",
    "privacy.section3.content": "未经您的同意，我们不会向第三方出售、交易或以其他方式转让您的个人信息，除非本政策中另有说明。我们可能会与协助我们运营网站和提供服务的服务提供商共享您的信息，或在法律要求时共享。",
    "privacy.section4.title": "数据安全",
    "privacy.section4.content": "我们实施适当的安全措施来保护您的个人信息免受未经授权的访问、更改、披露或破坏。然而，没有任何通过互联网传输或电子存储的方法是 100% 安全的。",
    "privacy.section5.title": "Cookie 和追踪",
    "privacy.section5.content": "我们使用 Cookie 和类似的追踪技术来增强您在我们网站上的体验、分析使用模式并个性化内容。您可以通过浏览器偏好设置控制 Cookie 设置。",
    "privacy.section6.title": "您的权利",
    "privacy.section6.content": "您有权访问、更新或删除您的个人信息。您也可以选择退出我们的某些通信。要行使这些权利，请使用下面提供的信息联系我们。",
    "privacy.section7.title": "本政策的变更",
    "privacy.section7.content": "我们可能会不时更新此隐私政策。我们将通过在此页面上发布新政策并更新最后修改日期来通知您任何变更。",
    "privacy.contact.title": "联系我们",
    "privacy.contact.content": "如果您对本隐私政策有任何疑问，请通过以下方式联系我们：",
    "privacy.contact.email": "zyrachains@gmail.com",
    "assets.search_placeholder": "按代码或发行者搜索...",
    "assets.testnet_warning": "Pi Network 主网数据。主网上尚无自定义资产。",
    "monitor.balance_trend": "余额趋势",
    "monitor.scanned": "已扫描",
    "home.monitors.wallets_tracked": "已追踪钱包",
    "home.monitors.current_balance": "当前余额",
    "home.monitors.net_24h": "24小时净变动",
    "home.monitors.total_out": "总流出",
    "home.monitors.confirmed_changes": "已确认变动",
    "home.monitors.starting_balance": "起始余额",
    "home.monitors.aggregate_balance_trend": "总余额趋势",
    "home.monitors.recent_balance_changes": "近期余额变动",
    "home.monitors.no_changes_recorded": "近期未记录变动。",
    "home.monitors.per_exchange_flow": "各交易所24小时资金流",
    "home.monitors.inflow": "流入",
    "home.monitors.outflow": "流出",
    "home.monitors.open_full_tracker": "打开完整{{type}}追踪器",
    "home.monitors.core_team_wallets": "核心团队钱包",
    "home.monitors.exchange_wallets": "交易所 (CEX) 钱包",
    "home.monitors.data_unavailable": "{{title}}数据暂时不可用。请确认监控服务正在运行。",

    // Zyra Social
    'social.title': 'Zyra 社交',
    'social.heading': 'Zyra 社交',
    'social.tagline': '分享创意，赚取奖励，建设社区',
    'social.viewFeed': '查看动态',
    'social.createPost': '发布帖子',
    'social.hub': '社交中心',
    'social.feed': '动态',
    'social.trending': '热门',
    'social.following': '关注',
    'social.new': '最新',
    'social.discover': '发现',
    'social.leaderboard': '排行榜',
    'social.badges': '徽章',
    'social.tokens': '代币',
    'social.earn': '赚取 ZP',
    'social.moderate': '审核',
    'social.profile': '个人资料',
    'social.search': '搜索...',
    'social.noPosts': '暂无帖子。成为第一个分享的人吧！',
    'social.noMorePosts': '没有更多帖子',
    'social.loading': '加载中...',
    'social.composer_placeholder': '你在想什么？',
    'social.composer_cost': '费用：{{cost}} ZP',
    'social.composer_balance': '余额：{{balance}} ZP',
    'social.composer_chars': '{{current}}/{{max}}',
    'social.composer_error_chars': '内容超过 {{max}} 个字符',
    'social.composer_error_balance': 'ZP 余额不足（需要 {{cost}} ZP）',
    'social.composer_error_required': '请输入内容',
    'social.composer_tags': '添加标签...',
    'social.post_submit': '发布',
    'social.posting': '发布中...',
    'social.post_cost': '{{cost}} ZP',
    'social.tip': '打赏',
    'social.tip_modal_title': '打赏创作者',
    'social.tip_creator': '打赏创作者',
    'social.tip_amount_label': '打赏给 @{{user}}...',
    'social.tip_min_error': '最低打赏 {{min}} ZP',
    'social.tip_send': '打赏 {{amount}} ZP',
    'social.tip_sending': '发送中...',
    'social.tip_creator_share': '创作者获得 80%（{{amount}} ZP）',
    'social.tip_earned': '已赚取 {{amount}} ZP',
    'social.boost': '推广',
    'social.boost_modal_title': '推广帖子',
    'social.boost_desc': '推广此帖子以增加曝光率和覆盖范围。50% 归创作者。',
    'social.boost_min_error': '最低推广 {{min}} ZP',
    'social.boost_duration': '推广持续时间 {{hours}} 小时',
    'social.boost_creator_share': '创作者获得 {{amount}} ZP',
    'social.boost_submit': '用 {{amount}} ZP 推广',
    'social.boosting': '推广中...',
    'social.promoted': '已推广',
    'social.like': '点赞',
    'social.comment': '评论',
    'social.reshare': '转发',
    'social.share': '分享',
    'social.report': '举报',
    'social.follow': '关注',
    'social.following_label': '已关注',
    'social.unfollow': '取消关注',
    'social.followers': '{{count}} 粉丝',
    'social.following_count': '关注了 {{count}} 人',
    'social.posts_count': '{{count}} 篇帖子',
    'social.buy_zp': '购买 Zyra Points',
    'social.buy_modal_title': '购买 Zyra Points',
    'social.buy_rate': '1 Pi = 100 ZP',
    'social.buy_pi_amount': 'Pi 金额',
    'social.buy_receive': '您将收到 {{amount}} ZP',
    'social.buy_current_balance': '当前余额：{{balance}} ZP',
    'social.buy_pay': '用 Pi 支付',
    'social.buy_processing': '处理中...',
    'social.buy_success': '付款已提交！确认后 ZP 将记入您的账户。',
    'social.ads_title': '观看并赚取 ZP',
    'social.ads_daily_limit': '每日限额',
    'social.ads_watched': '今日已观看',
    'social.ads_remaining': '剩余',
    'social.ads_limit_reached': '已达到每日广告限额。明天再来吧！',
    'social.ads_available': '可用广告',
    'social.ads_none': '暂无可用广告',
    'social.ads_watch': '观看',
    'social.ads_reward': '+{{amount}} ZP',
    'social.ads_earn_prompt': '观看以赚取 {{amount}} ZP',
    'social.ads_reward_ready': '奖励准备就绪！',
    'social.ads_please_wait': '请等待 {{seconds}} 秒...',
    'social.ads_reward_credited': '奖励已记入您的余额！',
    'social.ads_earned_toast': '+{{amount}} ZP 已赚取！',
    'social.moderate_title': '去中心化审核',
    'social.moderate_become': '成为审核员',
    'social.moderate_stake_desc': '质押 {{amount}} ZP 以获得审核员徽章并参与内容治理。正确投票获得奖励；错误投票失去质押。',
    'social.moderate_stake_btn': '质押 {{amount}} ZP',
    'social.moderate_votes': '投票',
    'social.moderate_accuracy': '准确率',
    'social.moderate_staked': '已质押',
    'social.moderate_queue': '被举报内容',
    'social.moderate_empty': '没有需要审核的被举报内容',
    'social.moderate_approve': '批准（{{stake}} ZP 质押）',
    'social.moderate_flag': '标记（{{stake}} ZP 质押）',
    'social.staked_success': '已质押 {{amount}} ZP。您现在是一名审核员。',
    'social.badge_earned': '已获得',
    'social.badge_purchase': '{{price}} ZP',
    'social.badge_special': '特殊',
    'social.badge_follower': '粉丝基础',
    'social.badge_achievement': '成就',
    'social.badge_premium': '高级徽章',
    'social.badge_moderation': '审核',
    'social.badge_yours': '您的徽章',
    'social.gamification_level': '等级 {{level}}',
    'social.gamification_xp': '{{xp}} XP',
    'social.gamification_streak': '连续 {{days}} 天',
    'social.gamification_daily_missions': '每日任务',
    'social.gamification_no_missions': '暂无任务',
    'social.gamification_claim': '+{{reward}} ZP',
    'social.leaderboard_title': '周排行榜',
    'social.leaderboard_empty': '本周暂无记录',
    'social.leaderboard_xp': 'XP',
    'social.leaderboard_total': '总计 {{xp}}',
    'social.balance': '余额',
    'social.balance_earned': '已赚取',
    'social.balance_purchased': '已购买',
    'social.balance_ad': '广告收入',
    'social.balance_spent': '总支出',
    'social.transactions_title': '交易记录',
    'social.transactions_empty': '暂无交易',
    'social.tx_purchase': '购买 ZP',
    'social.tx_post': '发布帖子',
    'social.tx_comment': '评论',
    'social.tx_like': '点赞',
    'social.tx_dislike': '踩',
    'social.tx_tip': '已发送打赏',
    'social.tx_reshare': '转发',
    'social.tx_boost': '推广',
    'social.tx_ad_reward': '广告奖励',
    'social.tx_mod_reward': '审核奖励',
    'social.tx_mod_loss': '审核质押损失',
    'social.tx_badge': '购买徽章',
    'social.tx_mission': '任务奖励',
    'social.tx_refund': '退款',
    'social.tx_platform_fee': '平台费用',
    'social.tx_creator_earning': '创作者收入',
    'social.comments_title': '评论',
    'social.comments_empty': '暂无评论。来发表第一条吧！',
    'social.comments_placeholder': '添加评论...（{{cost}} ZP）',
    'social.connect_prompt': '连接您的 Pi 账户以加入社区',
    'social.connect_feed': '连接您的 Pi 账户以查看动态',
    'social.connect_tokens': '连接您的 Pi 账户以管理代币',
    'social.connect_badges': '连接您的 Pi 账户以查看徽章',
    'social.connect_leaderboard': '连接您的 Pi 账户以查看排行榜',
    'social.connect_moderate': '连接您的 Pi 账户以参与审核',
    'social.connect_earn': '连接您的 Pi 账户以赚取 ZP',
    'social.connect_profile': '连接您的 Pi 账户以查看个人资料',
    'social.post_not_found': '未找到帖子',
    'social.profile_not_found': '未找到个人资料',
    'social.view_all_trending': '查看所有热门帖子',
    'social.no_posts_profile': '暂无帖子',
    'social.quick_stats': '快速统计',
    'social.impressions': '{{count}} 次浏览',
  }